export const spriteConfig = {
  icons: [
    'IconArrowRightShort',
    'IconBrandGithub',
    'IconChevronsNarrow',
    'IconChevron',
    'IconDiffSplit',
    'IconDiffUnified',
    'IconExpand',
    'IconExpandAll',
    'IconEyeSlash',
    'IconFileCode',
    'IconSymbolDiffstat',
    'IconSymbolAdded',
    'IconSymbolDeleted',
    'IconSymbolIgnored',
    'IconSymbolModified',
    'IconSymbolExtracted',
    'IconSymbolInlined',
    'IconSymbolMoved',
    'IconSymbolRef',
    'IconSymbolAddedFill',
    'IconSymbolDeletedFill',
    'IconSymbolDiffstatFill',
    'IconSymbolIgnoredFill',
    'IconSymbolModifiedFill',
    'IconSymbolExtractedFill',
    'IconSymbolInlinedFill',
    'IconSymbolMovedFill',
    'IconSymbolAddedDuo',
    'IconSymbolDeletedDuo',
    'IconSymbolDiffstatDuo',
    'IconSymbolExtractedDuo',
    'IconSymbolIgnoredDuo',
    'IconSymbolInlinedDuo',
    'IconSymbolModifiedDuo',
    'IconSymbolMovedDuo',
    'IconPlus',
  ],

  output: {
    file: 'packages/diffs/src/sprite.ts',
    symbolPrefix: 'diffs-icon-',
  },

  source: {
    extension: '.svg',
  },
};
