// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconBrandShiki({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <g clipPath="url(#a)">
        <path d="M16 2.88A2.88 2.88 0 0 0 13.12 0v2.88z" opacity={0.2} />
        <path d="M6.357 8.676q-.04-.508-.381-.793-.336-.285-1.022-.285-.437 0-.717.107a.86.86 0 0 0-.407.28.7.7 0 0 0-.137.406.67.67 0 0 0 .066.34.8.8 0 0 0 .254.27q.173.117.442.214.27.096.641.173l.854.183q.864.183 1.48.483.615.3 1.006.706.391.402.574.905.188.504.194 1.098-.006 1.027-.514 1.739-.508.711-1.454 1.083-.94.37-2.262.37-1.358 0-2.369-.4-1.006-.403-1.566-1.236-.555-.84-.559-2.145h2.684q.026.477.24.803.212.325.599.493.391.168.93.168.452 0 .758-.112.305-.112.462-.31a.73.73 0 0 0 .163-.453.64.64 0 0 0-.157-.417q-.148-.183-.489-.325a5 5 0 0 0-.92-.275l-1.037-.223q-1.383-.3-2.18-1.002-.794-.706-.789-1.926-.005-.992.53-1.734.537-.747 1.489-1.164.955-.417 2.19-.417 1.261 0 2.182.422.92.422 1.418 1.19.503.762.508 1.784z" />
        <path d="M13.12 16V0H9.28v16z" opacity={0.4} />
        <g opacity={0.6}>
          <path d="M16 2.88v3.84h-2.88V2.88zM9.28 2.88v3.84H0V2.88z" />
        </g>
      </g>
      <defs>
        <clipPath id="a">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </svg>
  );
}
