// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconThemes({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path
        d="M15.244 8.253a1 1 0 0 1-.366 1.366l-7.41 4.278 6.31-7.518q.12-.145.208-.304z"
        opacity={0.2}
      />
      <path
        d="M12.88 4.342a1 1 0 0 1 .124 1.41l-5.491 6.542 3.35-9.203q.065-.18.093-.364z"
        opacity={0.4}
      />
      <path
        d="M9.323 1.477a1 1 0 0 1 .598 1.282L7 10.783V1Q6.999.803 6.962.616z"
        opacity={0.6}
      />
      <path d="M5 0a1 1 0 0 1 1 1v12a3 3 0 1 1-6 0V1a1 1 0 0 1 1-1zM3 12a1 1 0 1 0 0 2 1 1 0 0 0 0-2" />
    </svg>
  );
}
