// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconDiffAddFill({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path d="m8.023 5.531 1.014 3.235h-2.11l1.02-3.235z" />
      <path
        fillRule="evenodd"
        d="M8 0c6.588 0 8 1.412 8 8s-1.412 8-8 8-8-1.412-8-8 1.412-8 8-8m.012 3.938c-.668 0-1.026.31-1.278 1.054L4.72 10.77c-.1.298-.14.48-.14.638 0 .399.298.662.732.662.421 0 .656-.216.82-.767l.445-1.36h2.807l.451 1.36c.158.545.404.767.832.767.451 0 .75-.27.75-.691 0-.164-.041-.357-.123-.61L9.277 4.993c-.252-.75-.603-1.054-1.265-1.054"
        clipRule="evenodd"
      />
    </svg>
  );
}
