// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconBullseye({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path d="M8 6a2 2 0 1 0 0 4 2 2 0 0 0 0-4m-.5 2a.5.5 0 1 1 1 0 .5.5 0 0 1-1 0" />
      <path d="M3 8a5 5 0 1 1 10 0A5 5 0 0 1 3 8m5-3.5a3.5 3.5 0 1 0 0 7 3.5 3.5 0 0 0 0-7" />
      <path d="M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-6.5a6.5 6.5 0 1 0 0 13 6.5 6.5 0 0 0 0-13" />
    </svg>
  );
}
