// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconTerminalBashFill({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path
        fillRule="evenodd"
        d="M8 0c6.588 0 8 1.412 8 8s-1.412 8-8 8-8-1.412-8-8 1.412-8 8-8m.5 10a.5.5 0 0 0 0 1H11a.5.5 0 0 0 0-1zM5 3.25a.5.5 0 0 0-.5.5v.308C3.684 4.244 3 4.877 3 5.75c0 .519.238.921.608 1.205.348.266.806.427 1.283.533.423.095.715.215.892.35.154.119.217.24.217.412C6 8.583 5.642 9 5 9s-1-.417-1-.75a.5.5 0 0 0-1 0c0 .873.684 1.505 1.5 1.691v.309a.5.5 0 0 0 1 0v-.309C6.316 9.755 7 9.123 7 8.25c0-.519-.238-.921-.608-1.205-.348-.266-.806-.427-1.283-.533-.423-.095-.715-.215-.892-.35C4.063 6.042 4 5.921 4 5.75 4 5.417 4.358 5 5 5s1 .417 1 .75a.5.5 0 0 0 1 0c0-.873-.684-1.506-1.5-1.692V3.75a.5.5 0 0 0-.5-.5"
        clipRule="evenodd"
      />
    </svg>
  );
}
