// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconConvo({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1.125);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 18 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path d="M14.977 6.406a5 5 0 0 1 2.05 7.559l.753.755a.75.75 0 0 1-.53 1.28H13a4.98 4.98 0 0 1-3.478-1.41 8 8 0 0 0 1.52-.689A3.5 3.5 0 0 0 13 14.5h2.443a.75.75 0 0 1 .032-1.025 3.496 3.496 0 0 0-.55-5.397 8 8 0 0 0 .051-1.672" />
      <path
        fillRule="evenodd"
        d="M7 0C8.03 0 9.013.224 9.896.626a7.02 7.02 0 0 1 3.834 4.443A7 7 0 0 1 7 14H.75a.75.75 0 0 1-.53-1.28l1.329-1.33A7 7 0 0 1 7 0m0 1.5a5.5 5.5 0 0 0-3.889 9.389.75.75 0 0 1 0 1.061l-.55.55H7a5.5 5.5 0 1 0 0-11"
        clipRule="evenodd"
      />
    </svg>
  );
}
