// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconMinusLg({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path d="M15 8a.75.75 0 0 0-.75-.75H1.75a.75.75 0 0 0 0 1.5h12.5A.75.75 0 0 0 15 8" />
    </svg>
  );
}
