// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconBrandGoogle({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path d="M15.545 6.559q.14.806.139 1.626c0 2.433-.87 4.492-2.384 5.884h.002C11.978 15.293 10.158 16 8 16A8 8 0 1 1 8 0a7.7 7.7 0 0 1 5.352 2.083l-2.284 2.284A4.35 4.35 0 0 0 8 3.167c-2.087 0-3.86 1.408-4.492 3.304a4.8 4.8 0 0 0 0 3.063h.003c.635 1.893 2.405 3.3 4.492 3.3 1.078 0 2.004-.275 2.722-.764h-.003a3.7 3.7 0 0 0 1.599-2.43H8V6.56z" />
    </svg>
  );
}
