// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconTextH1({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path d="M0 14V2h1.75v5.073h5.5V2H9v12H7.25V8.686h-5.5V14zm14.249 0V3.921h-.133L11 6V4.172L14.257 2H16v12z" />
    </svg>
  );
}
