// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconBrandCursor({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path d="M14.721 3.787 8.331.09a.66.66 0 0 0-.663 0L1.28 3.787A.56.56 0 0 0 1 4.272v7.457c0 .2.106.384.279.484l6.39 3.698a.66.66 0 0 0 .663 0l6.39-3.698a.56.56 0 0 0 .278-.484V4.272a.56.56 0 0 0-.279-.485m-.401.783L8.152 15.28c-.042.072-.152.043-.152-.04V8.226c0-.14-.075-.27-.196-.34L1.746 4.38c-.072-.041-.043-.152.04-.152h12.337c.175 0 .285.19.197.343" />
    </svg>
  );
}
