// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconPushed({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path
        fillRule="evenodd"
        d="M8 1.5a6.5 6.5 0 1 0 0 13 6.5 6.5 0 0 0 0-13M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8"
        clipRule="evenodd"
      />
      <path
        fillRule="evenodd"
        d="M7.47 4.22a.75.75 0 0 1 1.06 0l2.5 2.5a.75.75 0 1 1-1.06 1.06L8 5.81 6.03 7.78a.75.75 0 0 1-1.06-1.06z"
        clipRule="evenodd"
      />
      <path
        fillRule="evenodd"
        d="M7.47 8.22a.75.75 0 0 1 1.06 0l2.5 2.5a.75.75 0 1 1-1.06 1.06L8 9.81l-1.97 1.97a.75.75 0 0 1-1.06-1.06z"
        clipRule="evenodd"
      />
    </svg>
  );
}
