// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconCodeComments({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path d="M10.059 15H8.136l3.941-14H14zM3.923 15H2L5.941 1h1.923z" />
    </svg>
  );
}
