// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconInReviewRightFill({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path
        fillRule="evenodd"
        d="M8 0a8 8 0 0 1 6.162 13.102l1.618 1.618a.75.75 0 0 1-.53 1.28H8A8 8 0 1 1 8 0M5.75 7.875a1.375 1.375 0 1 1-2.75 0 1.375 1.375 0 0 1 2.75 0m3.625 0a1.375 1.375 0 1 1-2.75 0 1.375 1.375 0 0 1 2.75 0m2.25 1.375a1.375 1.375 0 1 0 0-2.75 1.375 1.375 0 0 0 0 2.75"
        clipRule="evenodd"
      />
    </svg>
  );
}
