// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconDiffModifiedFill({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path
        fillRule="evenodd"
        d="M8 0c6.588 0 8 1.412 8 8s-1.412 8-8 8-8-1.412-8-8 1.412-8 8-8m3.006 3.932c-.522 0-.815.228-1.09.955L8.041 9.545h-.059l-1.88-4.652c-.276-.721-.575-.961-1.084-.961-.569 0-.926.386-.926 1.025v6.264c0 .55.24.838.703.838s.72-.3.72-.838V6.68h.053l1.623 3.978c.217.54.457.727.82.727.358 0 .598-.176.815-.727L10.45 6.68h.053v4.54c0 .551.24.839.697.839.463 0 .72-.3.72-.838V4.957c0-.65-.333-1.025-.913-1.025"
        clipRule="evenodd"
      />
    </svg>
  );
}
