// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconTextItalics({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path d="M13 2.5h-2.79l-2.341 11H10.5V15h-7v-1.5h2.752l2.34-11H6V1h7z" />
    </svg>
  );
}
