// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconHunkDivider({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path
        fillRule="evenodd"
        d="M3.47 6.47a.75.75 0 0 1 1.06 0L6 7.94l1.47-1.47a.75.75 0 0 1 1.06 0L10 7.94l1.47-1.47a.75.75 0 0 1 1.06 0L14 7.94l.72-.72a.75.75 0 1 1 1.06 1.06l-1.25 1.25a.75.75 0 0 1-1.06 0L12 8.06l-1.47 1.47a.75.75 0 0 1-1.06 0L8 8.06 6.53 9.53a.75.75 0 0 1-1.06 0L4 8.06 2.53 9.53a.75.75 0 0 1-1.06 0L.22 8.28a.75.75 0 1 1 1.06-1.06l.72.72z"
        clipRule="evenodd"
      />
    </svg>
  );
}
