// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconCommit2({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1.125);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 18 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path
        fillRule="evenodd"
        d="M9 2a6 6 0 0 1 5.951 5.252L15 7.25h2.25a.75.75 0 0 1 0 1.5H15l-.049-.003a5.999 5.999 0 0 1-11.903 0L3 8.75H.75a.75.75 0 0 1 0-1.5H3l.048.002A6 6 0 0 1 9 2m0 1.5a4.5 4.5 0 1 0 0 9 4.5 4.5 0 0 0 0-9"
        clipRule="evenodd"
      />
    </svg>
  );
}
