// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconBrandTwitterX({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633zm-.86 13.028h1.36L4.323 2.145H2.865z" />
    </svg>
  );
}
