// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconSearch({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path d="M10.775 12.896a7 7 0 1 1 2.121-2.121l2.665 2.664a1.5 1.5 0 0 1-2.122 2.122zM7 1.5a5.5 5.5 0 1 1 0 11 5.5 5.5 0 0 1 0-11" />
    </svg>
  );
}
