// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconLaptop({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path d="M3.25 2A2.25 2.25 0 0 0 1 4.25v8.25h14V4.25A2.25 2.25 0 0 0 12.75 2zM2.5 4.25a.75.75 0 0 1 .75-.75h9.5a.75.75 0 0 1 .75.75V11h-11zM16 13H0a1.5 1.5 0 0 0 1.5 1.5h13A1.5 1.5 0 0 0 16 13" />
    </svg>
  );
}
