// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconGearFill({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path d="M9.095 1.058c-.108-1.41-2.182-1.41-2.29 0-.078 1.02-1.356 1.434-2.02.655-.919-1.078-2.597.137-1.853 1.342.538.871-.251 1.955-1.248 1.714C.305 4.435-.336 6.403.976 6.94c.949.39.949 1.729 0 2.118-1.312.538-.67 2.506.708 2.172.997-.24 1.786.843 1.248 1.714-.744 1.205.934 2.42 1.853 1.342.664-.78 1.942-.365 2.02.655.108 1.41 2.182 1.41 2.29 0 .078-1.02 1.356-1.434 2.02-.655.919 1.078 2.597-.137 1.853-1.342-.538-.871.251-1.955 1.248-1.714 1.379.334 2.02-1.634.708-2.172-.949-.39-.949-1.729 0-2.118 1.312-.538.67-2.506-.708-2.172-.997.24-1.786-.843-1.248-1.714.744-1.205-.934-2.42-1.853-1.342-.664.78-1.942.365-2.02-.655m-1.145 9.93A2.99 2.99 0 0 1 4.955 8 2.99 2.99 0 0 1 7.95 5.013 2.99 2.99 0 0 1 10.945 8a2.99 2.99 0 0 1-2.995 2.987" />
    </svg>
  );
}
