// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconWaiting({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path d="M8.5 3.75a.75.75 0 0 0-1.5 0v4.5c0 .276.151.53.394.66l3.25 1.75a.75.75 0 0 0 .712-1.32L8.5 7.802z" />
      <path d="M8 0a8 8 0 1 0 0 16A8 8 0 0 0 8 0M1.5 8a6.5 6.5 0 1 1 13 0 6.5 6.5 0 0 1-13 0" />
    </svg>
  );
}
