// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconDiffDeletedFill({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path d="M7.678 5.291c1.465 0 2.156.867 2.156 2.713 0 1.834-.686 2.701-2.156 2.701H6.54V5.291z" />
      <path
        fillRule="evenodd"
        d="M8 0c6.588 0 8 1.412 8 8s-1.412 8-8 8-8-1.412-8-8 1.412-8 8-8M6.014 4.002c-.703 0-1.055.334-1.055 1.014v5.97c0 .68.352 1.014 1.055 1.014h1.863c2.338 0 3.574-1.383 3.574-3.996 0-2.62-1.236-4.002-3.574-4.002z"
        clipRule="evenodd"
      />
    </svg>
  );
}
