// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconBrandVsCode({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <g clipPath="url(#a)">
        <g opacity={0.75}>
          <path d="M4.69 9.913 1.94 11.998a.67.67 0 0 1-.851-.037l-.881-.802a.667.667 0 0 1-.001-.986L2.59 8zM11 .333a.586.586 0 0 1 1 .414v3.62L7.212 8 4.69 6.086z" />
        </g>
        <g opacity={0.65}>
          <path d="m11.538 15.945.037.005zM1.09 4.04A.67.67 0 0 1 1.941 4L12 11.632v3.62a.586.586 0 0 1-1 .415L.208 5.827a.667.667 0 0 1 0-.986z" />
        </g>
        <path d="M12.137 15.86A1 1 0 0 1 11 15.667c.369.369 1 .107 1-.415V.748a.586.586 0 0 0-1-.415c.3-.3.755-.377 1.137-.193l3.296 1.585a1 1 0 0 1 .567.901v10.748a1 1 0 0 1-.567.901z" />
      </g>
      <defs>
        <clipPath id="a">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </svg>
  );
}
