// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconBrandZed({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <g clipPath="url(#a)">
        <path
          fillRule="evenodd"
          d="M1.5 1a.5.5 0 0 0-.5.5v11H0v-11A1.5 1.5 0 0 1 1.5 0h13.396a.75.75 0 0 1 .53 1.28l-8.25 8.251H9.5V8.5h1v1.281a.75.75 0 0 1-.75.75H6.176L4.457 12.25h7.793V6h1v6.25a1 1 0 0 1-1 1H3.457L1.707 15H14.5a.5.5 0 0 0 .5-.5v-11h1v11a1.5 1.5 0 0 1-1.5 1.5H1.104a.75.75 0 0 1-.53-1.28L8.792 6.5H6.5v1h-1V6.25a.75.75 0 0 1 .75-.75h3.543l1.75-1.75H3.75V10h-1V3.75a1 1 0 0 1 1-1h8.793L14.293 1z"
          clipRule="evenodd"
        />
      </g>
      <defs>
        <clipPath id="a">
          <path d="M0 0h16v16H0z" />
        </clipPath>
      </defs>
    </svg>
  );
}
