// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconSidebarOpen({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path d="M2.75 2.5c-.69 0-1.25.56-1.25 1.25v8.5c0 .69.56 1.25 1.25 1.25H8.5V15H2.75A2.75 2.75 0 0 1 0 12.25v-8.5A2.75 2.75 0 0 1 2.75 1H8.5v1.5zm7.5-1.5a.75.75 0 0 0-.75.75v12.5c0 .414.336.75.75.75h3A2.75 2.75 0 0 0 16 12.25v-8.5A2.75 2.75 0 0 0 13.25 1z" />
    </svg>
  );
}
