// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconCode({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path d="M9.403 1.266a.75.75 0 0 1 .581.887l-2.5 12a.75.75 0 1 1-1.468-.306l2.5-12a.75.75 0 0 1 .887-.581M4.8 4.24a.75.75 0 0 1-.04 1.06L1.852 8l2.908 2.7a.75.75 0 1 1-1.02 1.1L.24 8.55a.75.75 0 0 1 0-1.1l3.5-3.25a.75.75 0 0 1 1.06.04m6.4 0a.75.75 0 0 1 1.06-.04l3.5 3.25a.75.75 0 0 1 0 1.1l-3.5 3.25a.75.75 0 1 1-1.02-1.1L14.148 8 11.24 5.3a.75.75 0 0 1-.04-1.06" />
    </svg>
  );
}
