// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconCodeStyleInline({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path
        d="M2.25 13a.75.75 0 0 1 0 1.5H.75a.75.75 0 0 1 0-1.5zm1.92-3a1.74 1.74 0 0 0 0 1.5H2.75a.75.75 0 0 1 0-1.5zm9.08 0a.75.75 0 0 1 0 1.5h-2.42a1.74 1.74 0 0 0 0-1.5zM5.17 7a1.74 1.74 0 0 0 0 1.5H2.75a.75.75 0 0 1 0-1.5zm10.08 0a.75.75 0 0 1 0 1.5h-1.42a1.74 1.74 0 0 0 0-1.5zM4.17 4a1.74 1.74 0 0 0 0 1.5H2.75a.75.75 0 0 1 0-1.5zm7.08 0a.75.75 0 0 1 0 1.5H9.83a1.74 1.74 0 0 0 0-1.5zm-6-3a.75.75 0 0 1 0 1.5H.75a.75.75 0 0 1 0-1.5z"
        opacity={0.4}
      />
      <path d="M6 7.75A.75.75 0 0 1 6.75 7h5.5a.75.75 0 0 1 0 1.5h-5.5A.75.75 0 0 1 6 7.75m-1-3A.75.75 0 0 1 5.75 4h2.5a.75.75 0 0 1 0 1.5h-2.5A.75.75 0 0 1 5 4.75m0 6a.75.75 0 0 1 .75-.75h3.5a.75.75 0 0 1 0 1.5h-3.5a.75.75 0 0 1-.75-.75" />
    </svg>
  );
}
