// Generated by `bun run icons:build`, see README for details
import { Colors, type IconProps } from '../Color';

export function IconBulbFill({
  size = 16,
  color = 'currentcolor',
  style,
  className,
  ...props
}: IconProps) {
  const height = size;
  const width = size === '1em' ? '1em' : Math.round(Number(size) * 1);
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      fill={Colors[color] ?? color}
      viewBox="0 0 16 16"
      width={width}
      height={height}
      style={style}
      className={`pi${className != null ? ` ${className}` : ''}`}
      {...props}
    >
      <path d="M4.11 1.61a5.5 5.5 0 0 1 7.815 7.743l-.006.006-.029.03C11.777 9.516 11 10.45 11 12H5c0-1.55-.778-2.484-.89-2.611l-.029-.03-.005-.005A5.5 5.5 0 0 1 4.11 1.61M5 13a3 3 0 1 0 6 0z" />
    </svg>
  );
}
