'use client';

import type { PreloadedFileResult } from '@pierre/precision-diffs/ssr';

import { DocsCodeExample } from '../DocsCodeExample';

interface WorkerPoolProps {
  helperVite: PreloadedFileResult<undefined>;
  helperNextjs: PreloadedFileResult<undefined>;
  helperWebpack: PreloadedFileResult<undefined>;
  helperEsbuild: PreloadedFileResult<undefined>;
  helperStatic: PreloadedFileResult<undefined>;
  helperVanilla: PreloadedFileResult<undefined>;
  vanillaUsage: PreloadedFileResult<undefined>;
  reactUsage: PreloadedFileResult<undefined>;
  apiReference: PreloadedFileResult<undefined>;
}

export function WorkerPool({
  helperVite,
  helperNextjs,
  helperWebpack,
  helperEsbuild,
  helperStatic,
  helperVanilla,
  vanillaUsage,
  reactUsage,
  apiReference,
}: WorkerPoolProps) {
  return (
    <section className="space-y-4">
      <h2>Worker Pool</h2>
      <p>
        By default, syntax highlighting runs on the main thread using Shiki. If
        you are rendering large files or many diffs this can cause a bottleneck
        on your javascript thread resulting in jank or unresponsiveness. To work
        around this we've provided some APIs to run all syntax highlighting in
        worker threads. The main thread will still attempt to render plain text
        synchronously and then apply the syntax highlighting when we get a
        response from the worker threads.
      </p>
      <p>
        Basic usage differs a bit depending on if you're using React or Vanilla
        JS apis, so continue reading for more details.
      </p>

      <h3>Setup</h3>
      <p>
        One unfortunate side effect of using Web Workers is that different
        bundlers and environments require slightly different approaches to
        create a Web Worker. Basically you will need to create a function that
        spawns a worker that's appropriate for your environment and bundler and
        then pass that function to our provided APIs.
      </p>
      <p>
        To begin you'll need to create a function that can spawn a worker thread
        correctly for your bundler and environment. We've provided some examples
        for common use cases below.
      </p>
      <p>
        <em>
          Side note, we've only tested the Vite and NextJS examples, the rest
          were generated by AI. If any of them are incorrect, please let us know
        </em>
      </p>

      <h4 data-toc-ignore>Vite</h4>
      <DocsCodeExample {...helperVite} />

      <h4 data-toc-ignore>NextJS</h4>
      <p>
        <strong>Important:</strong> Workers only work in client components. Make
        sure your function has the <code>'use client'</code> directive if using
        App Router.
      </p>
      <DocsCodeExample {...helperNextjs} />

      <h4 data-toc-ignore>Webpack 5</h4>
      <DocsCodeExample {...helperWebpack} />

      <h4 data-toc-ignore>esbuild</h4>
      <DocsCodeExample {...helperEsbuild} />

      <h4 data-toc-ignore>Rollup / Static Files</h4>
      <p>
        If your bundler doesn't have special worker support, build and serve the
        worker file statically:
      </p>
      <DocsCodeExample {...helperStatic} />

      <h4 data-toc-ignore>Vanilla JS (No Bundler)</h4>
      <p>
        For projects without a bundler, host the worker file on your server and
        reference it directly:
      </p>
      <DocsCodeExample {...helperVanilla} />

      <h3>Usage</h3>
      <p>
        With your <code>workerFactory</code> function created, you can integrate
        it with our provided APIs. In React, you'll want to pass this{' '}
        <code>workerFactory</code> to a{' '}
        <code>&lt;WorkerPoolContextProvider&gt;</code> so all components can
        inherit the pool automatically. If you're using the Vanilla JS APIs we
        provide a <code>getOrCreateWorkerPoolSingleton</code> helper that
        ensures a single pool instance that you can then manually pass to all
        your File/FileDiff instances.
      </p>

      <h4>React</h4>
      <p>
        Wrap your component tree with <code>WorkerPoolContextProvider</code>{' '}
        from <code>@pierre/precision-diffs/react</code>. All{' '}
        <code>FileDiff</code> and <code>File</code> components nested within
        will automatically use the worker pool for syntax highlighting.
      </p>
      <p>
        <strong>Important:</strong> The worker pool only works in client
        components. Make sure your provider is in a component with the{' '}
        <code>'use client'</code> directive if you're using NextJS App Router.
        Workers cannot be instantiated during server-side rendering.
      </p>
      <DocsCodeExample {...reactUsage} />

      <h4>Vanilla JS</h4>
      <p>
        Once you've instantiated your worker pool, pass it directly to your{' '}
        <code>File</code> and <code>FileDiff</code> constructors via the{' '}
        <code>workerPool</code> option.
      </p>
      <DocsCodeExample {...vanillaUsage} />

      <h3>API Reference</h3>
      <p>
        These methods are exposed for advanced use cases. In most scenarios, you
        should use the <code>WorkerPoolContextProvider</code> for React or pass
        the pool instance via the <code>workerPool</code> option for Vanilla JS
        rather than calling these methods directly.
      </p>
      <DocsCodeExample {...apiReference} />

      <h3>Architecture</h3>
      <p>
        The worker pool manages a configurable number of worker threads that
        each initialize their own Shiki highlighter instance. Tasks are
        distributed across available workers, with queuing when all workers are
        busy.
      </p>
      <code
        className="m-0 inline-block overflow-x-auto rounded-lg bg-neutral-100 p-4 text-sm font-normal whitespace-pre dark:bg-neutral-900"
        style={{ fontFamily: 'Berkeley Mono, monospace', lineHeight: '16px' }}
      >
        {`
┌────────────── Main Thread ──────────────┐
│ ┌ React (if used) ────────────────────┐ │
│ │ <WorkerPoolContextProvider>         │ │
│ │   <FileDiff />                      │ │
│ │   <File />                          │ │
│ │ </WorkerPoolContextProvider>        │ │
│ └─┬───────────────────────────────────┘ │
│   ↓ (each manage their own instances)   │
│ ┌ Vanilla JS Classes ─────────────────┐ │
│ │ new FileDiff(opts, poolManager)     │ │
│ │ new File(opts, poolManager)         │ │
│ │ * Renders plain text synchronously  │ │
│ │ * Queue requests to WorkerPool for  │ │
│ │   highlighted HAST                  │ │
│ │ * Automatically render the          │ │
│ │   highlighted HAST response         │ │
│ └─┬───────────────────────────────────┘ │
│   ↓ (Request)         HAST Response ↑   │
│ ┌───────────────────────────────────┴─┐ │
│ │ ShikiPoolManager                    │ │
│ │ * Shared singleton                  │ │
│ │ * Manages WorkerPool instance and   │ │
│ │   request queue                     │ │
│ └─┬─────────────────────────────────┬─┘ │
└───┼─────────────────────────────────┼───┘
    ↓ postMessage       HAST Response ↑
┌───┼───────── Worker Threads ────────┼───┐
│ ┌─┴─ shiki-worker.js (8x default) ──┴─┐ │
│ │ * Runs Shiki's codeToHast()         │ │
│ │ * Manages themes and language       │ │
│ │   loading automatically             │ │
│ └─────────────────────────────────────┘ │
└─────────────────────────────────────────┘
`.trim()}
      </code>
    </section>
  );
}
