#!/usr/bin/env bun
import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { resolve as resolvePath } from 'node:path';

// Builds the canned data for the homepage agent-review demo from THIS repo, so
// the diffs shown in the card are real code. The single live session is
// self-referential: it's the agent "building" the demo, and its changed files
// are the actual source files the demo is made of.
//
// Output is a committed snapshot (no runtime fs/git, so it works on Vercel). It
// can drift from the live repo over time; re-run to refresh:
//
//   bun apps/docs/scripts/generate-aui-mock-data.ts

const repoRoot = resolvePath(import.meta.dirname, '../../..');
const outputPath = resolvePath(
  repoRoot,
  'apps/docs/app/(diffs)/_home/mockData.generated.ts'
);

// The source files that make up the homepage agent-review demo. The generated
// blob itself is deliberately excluded to avoid self-nesting and bloat.
const SELF_SESSION_FILES = [
  'apps/docs/app/(diffs)/_home/AgentUi.tsx',
  'apps/docs/app/(diffs)/_home/AgentDemoSection.tsx',
  'apps/docs/app/(diffs)/_home/mockData.ts',
  'apps/docs/app/(diffs)/_home/agent-ui.css',
  'apps/docs/scripts/generate-aui-mock-data.ts',
  '.agents/skills/agent-ui/SKILL.md',
] as const;

interface GeneratedChangedFile {
  path: string;
  status: 'added' | 'modified';
  before: string;
  after: string;
  additions: number;
  deletions: number;
}

interface GeneratedSession {
  id: string;
  title: string;
  subtitle: string;
  status: 'running' | 'review' | 'done';
  changedFiles: GeneratedChangedFile[];
}

// Returns the file contents at HEAD, or null when the path is new (not tracked
// in the last commit).
function gitShowHead(path: string): string | null {
  try {
    return execFileSync('git', ['show', `HEAD:${path}`], {
      cwd: repoRoot,
      encoding: 'utf8',
      maxBuffer: 64 * 1024 * 1024,
    });
  } catch {
    return null;
  }
}

// Parses `git diff --numstat HEAD` for a single path. Returns null when git has
// nothing to report (e.g. an untracked new file).
function gitNumstat(
  path: string
): { additions: number; deletions: number } | null {
  try {
    const out = execFileSync('git', ['diff', '--numstat', 'HEAD', '--', path], {
      cwd: repoRoot,
      encoding: 'utf8',
    }).trim();
    if (out.length === 0) {
      return null;
    }
    const [additions, deletions] = out.split('\n')[0].split('\t');
    if (additions === '-' || deletions === '-') {
      return null;
    }
    return { additions: Number(additions), deletions: Number(deletions) };
  } catch {
    return null;
  }
}

function countLines(contents: string): number {
  if (contents.length === 0) {
    return 0;
  }
  const lines = contents.split('\n');
  return contents.endsWith('\n') ? lines.length - 1 : lines.length;
}

function buildChangedFile(path: string): GeneratedChangedFile {
  const after = readFileSync(resolvePath(repoRoot, path), 'utf8');
  const head = gitShowHead(path);
  const status: GeneratedChangedFile['status'] =
    head == null ? 'added' : 'modified';
  const before = head ?? '';
  const numstat = gitNumstat(path);
  const additions = numstat?.additions ?? countLines(after);
  const deletions = numstat?.deletions ?? 0;
  return { path, status, before, after, additions, deletions };
}

const selfSession: GeneratedSession = {
  id: 'aui-self',
  title: 'Add agent-review demo',
  subtitle: 'Ready for review',
  status: 'review',
  changedFiles: SELF_SESSION_FILES.map((path) => {
    console.log(`[aui] capturing ${path}`);
    return buildChangedFile(path);
  }),
};

const sessions: GeneratedSession[] = [selfSession];

const header = `// AUTO-GENERATED by apps/docs/scripts/generate-aui-mock-data.ts. Do not edit by
// hand. Re-run the generator to refresh this snapshot from the live repo.
import type { AuiSession } from './mockData';

export const GENERATED_AUI_SESSIONS: AuiSession[] = `;

writeFileSync(
  outputPath,
  `${header}${JSON.stringify(sessions, null, 2)};\n`,
  'utf8'
);

const totalFiles = sessions.reduce(
  (count, session) => count + session.changedFiles.length,
  0
);
console.log(
  `[aui] wrote ${String(sessions.length)} session(s), ${String(totalFiles)} files -> ${outputPath}`
);
