/**
 * One realistic, multi-line source sample per built-in lexer, shared by the
 * cross-language conformance suite. Every sample mixes the constructs a lexer
 * must get right - comments (line and block), strings with escapes, numbers in
 * several bases, keywords, declarations, calls, operators, punctuation - plus
 * at least one construct that spans lines, so line-fed streaming has state to
 * carry across chunks.
 *
 * `kinds` lists the `$Token` names the lexer must produce for the sample. The
 * list is a floor, not an exact set: it documents which classifications the
 * sample exercises so a regression that silently drops a kind (a keyword
 * table that stops matching, a string machine that swallows a comment) fails
 * loudly. Keep the kinds in the order they first appear in the sample.
 */

/** Join lines with `\n` and end with a trailing newline, like a saved file. */
const lines = (...ls: string[]): string => ls.join('\n') + '\n';

export interface LangSample {
  code: string;
  kinds: readonly string[];
}

export const samples: Record<string, LangSample> = {
  asm: {
    code: lines(
      '.section .text',
      '.globl main',
      '# entry point',
      'main:',
      '    push rbp',
      '    mov rbp, rsp',
      '    mov eax, 0x2A       ; the answer',
      '    lea rdi, [rip + msg]',
      '    call puts',
      '    xor eax, eax',
      '    /* multi',
      '       line */',
      '    add r0, r1, #4',
      '    mov $-8, %rax',
      '    pop rbp',
      '    ret',
      'msg:',
      '    .asciz "hello, world\\n"',
      '    .byte 0x1, 2, -3'
    ),
    kinds: [
      'preproc',
      'variable',
      'comment',
      'label',
      'punctuation.delimiter',
      'keyword',
      'variable.special',
      'number',
      'punctuation.bracket',
      'operator',
      'string',
      'string.escape',
    ],
  },
  astro: {
    code: lines(
      '---',
      "import Layout from '../layouts/Layout.astro';",
      'const { title = "Home" } = Astro.props;',
      'const items: string[] = await fetch(url).then((r) => r.json());',
      '---',
      '<Layout title={title}>',
      '  <h1 class="heading">{title.toUpperCase()}</h1>',
      '  <!-- list -->',
      '  <ul>',
      '    {items.map((item) => <li key={item}>{item}</li>)}',
      '  </ul>',
      '  <Counter client:load initial={1} />',
      '</Layout>',
      '<style>',
      '  .heading { color: #ff0000; font-size: 2rem; }',
      '</style>',
      '<script>',
      '  console.log("hydrated", 42);',
      '</script>'
    ),
    kinds: [
      'punctuation.special',
      'keyword.import',
      'type',
      'string',
      'punctuation.delimiter',
      'keyword.declaration',
      'punctuation.bracket',
      'variable',
      'property',
      'type.builtin',
      'keyword.control',
      'function',
      'function.method',
      'variable.parameter',
      'punctuation.bracket.html',
      'tag',
      'attribute',
      'punctuation.delimiter.html',
      'comment',
      'punctuation.bracket.jsx',
      'tag.jsx',
      'attribute.jsx',
      'punctuation.delimiter.jsx',
      'number',
      'selector.class',
      'string.special',
    ],
  },
  bash: {
    code: lines(
      '#!/usr/bin/env bash',
      'set -euo pipefail',
      '# usage: build.sh <target>',
      'target="${1:-all}"',
      'count=0',
      'build() {',
      '  local dir=$1',
      '  if [[ -d "$dir" && $count -lt 10 ]]; then',
      '    echo "building $dir at $(date +%s)"',
      '    (( count++ ))',
      '  elif [ "$dir" == \'skip\' ]; then',
      '    return 1',
      '  fi',
      '}',
      'for f in src/*.c; do',
      '  build "$f" || exit $?',
      'done',
      'cat <<EOF > out.txt',
      'total: $count',
      'EOF',
      'case "$target" in',
      '  all|clean) make "$target" ;;',
      '  *) printf "%s\\n" "unknown" >&2 ;;',
      'esac'
    ),
    kinds: [
      'comment',
      'function',
      'variable',
      'operator',
      'string',
      'punctuation.special',
      'number',
      'function.definition',
      'punctuation.bracket',
      'keyword.declaration',
      'keyword.control',
      'string.special',
      'string.escape',
    ],
  },
  c: {
    code: lines(
      '#include <stdio.h>',
      '#include "util.h"',
      '#define MAX(a, b) ((a) > (b) ? (a) : (b))',
      '',
      '/* A linked list node. */',
      'typedef struct node {',
      '    int value;',
      '    struct node *next;',
      '} node_t;',
      '',
      'static int sum(const node_t *head) {',
      '    int total = 0;',
      '    for (; head != NULL; head = head->next)',
      '        total += head->value;',
      '    return total;',
      '}',
      '',
      'int main(int argc, char **argv) {',
      '    node_t a = { .value = 0x1F, .next = NULL };',
      '    unsigned long big = 1000000UL;',
      '    double ratio = 3.5e-2;',
      "    char c = '\\n';",
      '    // print the result',
      '    printf("sum=%d %s\\n", sum(&a), argv[0]);',
      '    return big > MAX(1, 2) ? 0 : 1;',
      '}'
    ),
    kinds: [
      'preproc',
      'string',
      'comment',
      'keyword.declaration',
      'type.builtin',
      'variable',
      'punctuation.bracket',
      'punctuation.delimiter',
      'operator',
      'type',
      'function',
      'keyword',
      'number',
      'keyword.control',
      'constant',
      'string.escape',
    ],
  },
  c3: {
    code: lines(
      'module demo::app;',
      'import std::io;',
      '<* Doc comment',
      '   across lines *>',
      'const int MAX = 10;',
      'struct Point { int x; int y; }',
      'macro @swap(&a, &b) { $typeof(a) tmp = a; a = b; b = tmp; }',
      'fn void Point.scale(&self, int k) @inline { self.x *= k; }',
      'fn int! divide(int a, int b) {',
      '  $if $defined(a): return a / b; $endif',
      '  List{int} list; io::printn("x\\n");',
      '  char c = \'a\'; char[] h = x"41"; int n = 0x1F + 1_000u;',
      '  String s = `raw',
      'string`; // note',
      '  foreach (i, v : list) { defer io::printfn("%d", v); }',
      '  /* a /* nested */ b */',
      '  return a ?? 0;',
      '}'
    ),
    kinds: [
      'keyword.declaration',
      'namespace',
      'punctuation.delimiter',
      'keyword.import',
      'comment.doc',
      'type.builtin',
      'constant',
      'operator',
      'number',
      'type',
      'punctuation.bracket',
      'variable',
      'attribute',
      'keyword',
      'function.definition',
      'property',
      'keyword.control',
      'function',
      'string',
      'string.escape',
      'comment',
    ],
  },
  cpp: {
    code: lines(
      '#include <vector>',
      '#include <string>',
      'namespace app {',
      'template <typename T>',
      'class Stack final : public Base {',
      'public:',
      '    explicit Stack(std::size_t cap) : cap_(cap) {}',
      '    void push(T&& v) { items_.push_back(std::move(v)); }',
      '    [[nodiscard]] auto size() const noexcept -> std::size_t { return items_.size(); }',
      'private:',
      '    std::vector<T> items_;',
      '    std::size_t cap_;',
      '};',
      '} // namespace app',
      '',
      'int main() {',
      '    auto s = app::Stack<std::string>{16};',
      '    s.push("hello\\t");',
      '    const char* raw = R"(raw "text"',
      '      across lines)";',
      '    constexpr int mask = 0xFFu | 0b1010;',
      '    /* block',
      '       comment */',
      '    for (auto& x : {1, 2, 3}) if (x != 2) s.push(std::to_string(x));',
      '    return nullptr == raw ? -1 : 0;',
      '}'
    ),
    kinds: [
      'preproc',
      'string',
      'keyword.declaration',
      'namespace',
      'punctuation.bracket',
      'operator',
      'keyword',
      'type',
      'type.class',
      'punctuation.delimiter',
      'function',
      'variable',
      'type.builtin',
      'function.method',
      'property',
      'keyword.control',
      'comment',
      'number',
      'string.escape',
      'constant.builtin',
    ],
  },
  csharp: {
    code: lines(
      'using System;',
      'using System.Collections.Generic;',
      '#nullable enable',
      '',
      'namespace Demo',
      '{',
      '    /// <summary>A counter.</summary>',
      '    public sealed class Counter<T> : ICounter where T : struct',
      '    {',
      '        private readonly List<T> _items = new();',
      '        public int Count => _items.Count;',
      '        [Obsolete("use Add")]',
      '        public async Task<bool> AddAsync(T item, CancellationToken ct = default)',
      '        {',
      '            var text = $"added {item} at {DateTime.Now:HH:mm}";',
      '            string path = @"C:\\temp',
      '                across lines";',
      '            const double ratio = 1.5e3;',
      '            /* block */',
      '            if (item is null || Count > 0xFF) return false;',
      '            await Task.Delay(10, ct);',
      '            return true; // done',
      '        }',
      '    }',
      '}'
    ),
    kinds: [
      'keyword.import',
      'namespace',
      'punctuation.delimiter',
      'preproc',
      'keyword.declaration',
      'punctuation.bracket',
      'comment.doc',
      'type',
      'operator',
      'variable',
      'keyword.operator',
      'type.builtin',
      'attribute',
      'string',
      'function.definition',
      'keyword.control',
      'punctuation.special',
      'constant',
      'number',
      'comment',
      'constant.builtin',
      'boolean',
      'function.method',
    ],
  },
  css: {
    code: lines(
      '@import url("base.css");',
      ':root { --gap: 8px; }',
      '/* layout',
      '   rules */',
      '.card > .title:hover, #main::before {',
      '  color: #ff8800;',
      '  margin: calc(var(--gap) * 2) 1.5rem;',
      "  background: url('img.png') no-repeat;",
      '  content: "\\201C";',
      '  transition: opacity 0.3s ease-in-out !important;',
      '}',
      '@media (min-width: 640px) and (prefers-color-scheme: dark) {',
      '  a[href^="https"] { font-weight: 700; }',
      '}',
      '@keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }'
    ),
    kinds: [
      'keyword',
      'function',
      'punctuation.bracket',
      'string',
      'punctuation.delimiter',
      'selector.pseudo',
      'variable',
      'number',
      'comment',
      'selector.class',
      'operator',
      'selector.id',
      'property',
      'string.special',
      'constant.builtin',
      'string.escape',
      'keyword.operator',
      'tag',
      'attribute',
    ],
  },
  dart: {
    code: lines(
      "import 'dart:async';",
      "import 'package:flutter/material.dart';",
      '',
      '/// A counter widget.',
      'class Counter extends StatefulWidget {',
      '  final int initial;',
      '  const Counter({super.key, this.initial = 0});',
      '  @override',
      '  State<Counter> createState() => _CounterState();',
      '}',
      '',
      'class _CounterState extends State<Counter> {',
      '  late int _count = widget.initial;',
      '  Future<void> _increment() async {',
      '    await Future.delayed(const Duration(milliseconds: 100));',
      '    setState(() => _count += 1);',
      "    print('''count is",
      "$_count and ${_count * 2}''');",
      '  }',
      '  @override',
      '  Widget build(BuildContext context) {',
      '    final double ratio = 0x1F / 2.5e1;',
      '    var ok = _count > 3 && ratio != null ? true : false;',
      '    /* block',
      '       comment */',
      '    return Text("$_count", key: const ValueKey(\'c\')); // build',
      '  }',
      '}'
    ),
    kinds: [
      'keyword.import',
      'string',
      'punctuation.delimiter',
      'comment.doc',
      'keyword.declaration',
      'type',
      'punctuation.bracket',
      'type.builtin',
      'variable',
      'variable.special',
      'property',
      'operator',
      'number',
      'attribute',
      'function.definition',
      'function',
      'keyword.control',
      'function.method',
      'punctuation.special',
      'constant.builtin',
      'boolean',
      'comment',
    ],
  },
  diff: {
    code: lines(
      'diff --git a/src/config.js b/src/config.js',
      'similarity index 88%',
      'rename from src/old.js',
      'rename to src/config.js',
      'index 1a2b3c4..5d6e7f8 100644',
      '--- a/src/config.js',
      '+++ b/src/config.js',
      '@@ -1,4 +1,5 @@ export const config',
      ' export const config = {',
      '-  mode: "slow",',
      '+  mode: "simd",',
      '+  batchSize: 16,',
      ' };',
      '# generated patch',
      'new file mode 100644',
      'deleted file mode 100755',
      'Binary files a/image.png and b/image.png differ'
    ),
    kinds: [
      'function',
      'variable.parameter',
      'label',
      'number',
      'keyword',
      'constant',
      'punctuation.special',
      'diff.minus',
      'diff.plus',
      'attribute',
      'comment',
    ],
  },
  dockerfile: {
    code: lines(
      '# syntax=docker/dockerfile:1',
      'ARG NODE_VERSION=20',
      'FROM node:${NODE_VERSION}-alpine AS build',
      'WORKDIR /app',
      'COPY package*.json ./',
      'RUN npm ci --omit=dev \\',
      '    && npm cache clean --force',
      'ENV PORT=8080 \\',
      '    NODE_ENV="production"',
      'EXPOSE 8080',
      'HEALTHCHECK --interval=30s CMD curl -f http://localhost:$PORT/ || exit 1',
      'RUN <<EOF',
      'echo "multi line"',
      'apk add --no-cache curl',
      'EOF',
      'USER node',
      'ENTRYPOINT ["node", "server.js"]',
      "CMD ['--port', '8080']"
    ),
    kinds: [
      'comment',
      'keyword',
      'operator',
      'variable',
      'function',
      'variable.parameter',
      'punctuation.special',
      'string',
      'number',
      'string.special',
      'punctuation.bracket',
      'punctuation.delimiter',
    ],
  },
  elixir: {
    code: lines(
      'defmodule Shop.Cart do',
      '  @moduledoc """',
      '  A shopping cart.',
      '  """',
      '  use GenServer',
      '  alias Shop.Item',
      '  @max_items 100',
      '',
      '  defstruct items: [], total: 0.0',
      '',
      '  # add an item',
      '  def add(%__MODULE__{items: items} = cart, %Item{price: price} = item) when price > 0 do',
      '    %{cart | items: [item | items], total: cart.total + price}',
      '  end',
      '',
      '  def summary(cart), do: "#{length(cart.items)} items, total: #{cart.total}"',
      '',
      '  @impl true',
      '  def handle_call({:add, item}, _from, state) do',
      '    case add(state, item) do',
      '      %{total: t} = new when t < @max_items -> {:reply, :ok, new}',
      '      _ -> {:reply, {:error, ~s(too many)}, state}',
      '    end',
      '  end',
      '',
      '  defp price?(x), do: is_number(x) and x >= 0x10 or x == nil',
      'end'
    ),
    kinds: [
      'keyword.declaration',
      'type',
      'punctuation.delimiter',
      'keyword.control',
      'attribute',
      'comment.doc',
      'keyword.import',
      'number',
      'string.special.symbol',
      'punctuation.bracket',
      'comment',
      'function.definition',
      'punctuation.special',
      'variable.special',
      'variable',
      'operator',
      'keyword.operator',
      'property',
      'string',
      'function',
      'boolean',
      'constant.builtin',
    ],
  },
  erlang: {
    code: lines(
      '-module(shop).',
      '-export([start/0, add/2]).',
      '-record(item, {name, price = 0}).',
      '-define(MAX, 100).',
      '',
      '%% start the server',
      'start() ->',
      '    Pid = spawn(fun() -> loop([]) end),',
      '    register(?MODULE, Pid),',
      '    {ok, Pid}.',
      '',
      'add(Name, Price) when is_integer(Price), Price > 0 ->',
      '    ?MODULE ! {add, #item{name = Name, price = Price}},',
      '    io:format("added ~s at ~p~n", [Name, Price * 1.5e2]);',
      'add(_, _) ->',
      '    {error, badarg}.',
      '',
      'loop(Items) ->',
      '    receive',
      '        {add, #item{price = P} = I} when length(Items) < ?MAX ->',
      '            loop([I | Items]);',
      "        stop -> $a + 16#FF, 'quoted atom', true",
      '    after 5000 -> loop(Items)',
      '    end.'
    ),
    kinds: [
      'keyword',
      'punctuation.bracket',
      'namespace',
      'punctuation.delimiter',
      'function',
      'operator',
      'number',
      'type',
      'string.special.symbol',
      'constant',
      'comment',
      'function.definition',
      'variable',
      'keyword.control',
      'keyword.operator',
      'punctuation.special',
      'string',
      'string.special',
      'boolean',
    ],
  },
  gleam: {
    code: lines(
      'import gleam/io',
      'import gleam/list',
      'import gleam/option.{type Option, None, Some}',
      '',
      '/// A shape.',
      'pub type Shape {',
      '  Circle(radius: Float)',
      '  Rect(width: Float, height: Float)',
      '}',
      '',
      'pub fn area(shape: Shape) -> Float {',
      '  case shape {',
      '    Circle(r) -> 3.14 *. r *. r',
      '    Rect(w, h) -> w *. h',
      '  }',
      '}',
      '',
      'pub fn main() {',
      '  let shapes = [Circle(1.0), Rect(2.0, 3.5)]',
      '  let total = shapes |> list.map(area) |> list.fold(0.0, fn(a, b) { a +. b })',
      '  // print it',
      '  io.println("total: \\n" <> string.inspect(total))',
      '  let assert Some(first) = list.first(shapes)',
      '  let n = 0xFF + 1_000',
      '  use x <- result.try(Ok(n))',
      '  Ok(x)',
      '}'
    ),
    kinds: [
      'keyword.import',
      'namespace',
      'punctuation.delimiter',
      'punctuation.bracket',
      'keyword.declaration',
      'type',
      'comment.doc',
      'constructor',
      'variable.parameter',
      'function.definition',
      'operator',
      'keyword.control',
      'variable',
      'number',
      'function.method',
      'comment',
      'string',
      'string.escape',
    ],
  },
  glsl: {
    code: lines(
      '#version 330 core',
      '#define PI 3.14159',
      'layout(location = 0) in vec3 aPos;',
      'uniform mat4 uModel;',
      'out vec4 vColor;',
      '',
      '/* compute',
      '   lighting */',
      'float lambert(vec3 n, vec3 l) {',
      '    return max(dot(normalize(n), l), 0.0);',
      '}',
      '',
      'void main() {',
      '    vec4 pos = uModel * vec4(aPos, 1.0);',
      '    float d = lambert(vec3(0.0, 1.0, 0.0), vec3(1, 0, 0));',
      '    // branch',
      '    if (d > 0.5 && gl_VertexID != 2) discard;',
      '    for (int i = 0; i < 4; ++i) pos.x += float(i) * 0.25;',
      '    vColor = vec4(d, d, d, 1.0);',
      '    gl_Position = pos;',
      '    bool ok = true;',
      '}'
    ),
    kinds: [
      'preproc',
      'number',
      'variable',
      'constant',
      'keyword',
      'punctuation.bracket',
      'operator',
      'type.builtin',
      'punctuation.delimiter',
      'comment',
      'function',
      'keyword.control',
      'variable.special',
      'property',
      'boolean',
    ],
  },
  go: {
    code: lines(
      'package main',
      '',
      'import (',
      '\t"fmt"',
      '\t"strings"',
      ')',
      '',
      '// Shape is anything with an area.',
      'type Shape interface {',
      '\tArea() float64',
      '}',
      '',
      'type Rect struct{ W, H float64 }',
      '',
      'func (r Rect) Area() float64 { return r.W * r.H }',
      '',
      'func main() {',
      '\tshapes := []Shape{Rect{2, 3}, Rect{W: 1.5, H: 0x10}}',
      '\ttotal := 0.0',
      '\tfor i, s := range shapes {',
      '\t\ttotal += s.Area()',
      '\t\tfmt.Printf("%d: %.2f\\n", i, s.Area())',
      '\t}',
      '\traw := `multi',
      'line`',
      '\tif len(raw) > 3 && total != 0 {',
      "\t\tfmt.Println(strings.ToUpper(raw), 'x', nil, true)",
      '\t}',
      '\tdefer fmt.Println("done")',
      '\t/* block',
      '\t   comment */',
      '\tgo func() { panic("boom") }()',
      '}'
    ),
    kinds: [
      'keyword.declaration',
      'namespace',
      'keyword.import',
      'punctuation.bracket',
      'string',
      'comment',
      'type',
      'function',
      'type.builtin',
      'punctuation.delimiter',
      'variable',
      'function.definition',
      'keyword.control',
      'property',
      'operator',
      'number',
      'function.method',
      'string.escape',
      'constant.builtin',
      'boolean',
    ],
  },
  graphql: {
    code: lines(
      '# schema',
      'schema { query: Query mutation: Mutation }',
      '',
      '"""',
      'A user of the system.',
      '"""',
      'type User implements Node @key(fields: "id") {',
      '  id: ID!',
      '  name: String',
      '  posts(first: Int = 10, after: String): [Post!]!',
      '}',
      '',
      'enum Role { ADMIN EDITOR }',
      'input NewPost { title: String!, tags: [String!] = [] }',
      '',
      'query GetUser($id: ID!, $withPosts: Boolean = false) {',
      '  user(id: $id) {',
      '    ...UserFields',
      '    posts(first: 5) @include(if: $withPosts) { title }',
      '  }',
      '}',
      '',
      'fragment UserFields on User { id name }',
      'mutation { createPost(input: { title: "Hi", tags: ["a"] }) { id } }'
    ),
    kinds: [
      'comment',
      'keyword',
      'punctuation.bracket',
      'property',
      'punctuation.delimiter',
      'type',
      'string',
      'attribute',
      'variable.parameter',
      'type.builtin',
      'operator',
      'function',
      'number',
      'constant',
      'function.definition',
      'variable',
      'boolean',
      'punctuation.special',
    ],
  },
  haskell: {
    code: lines(
      '{-# LANGUAGE ScopedTypeVariables #-}',
      'module Shop (total, Item(..)) where',
      '',
      'import qualified Data.Map as M',
      "import Data.List (foldl')",
      '',
      '-- | An item for sale.',
      'data Item = Item { name :: String, price :: Double } deriving (Show, Eq)',
      '',
      'class Priced a where',
      '  cost :: a -> Double',
      '',
      'instance Priced Item where',
      '  cost = price',
      '',
      '{- block',
      '   comment -}',
      'total :: [Item] -> Double',
      "total = foldl' (\\acc i -> acc + cost i) 0",
      '',
      'main :: IO ()',
      'main = do',
      '  let items = [Item "tea" 2.5, Item "cake" 0x10]',
      '      n = length items `div` 2',
      '  case items of',
      '    (x:_) | price x > 1 -> putStrLn $ "first: " ++ name x',
      '    _ -> return ()',
      '  print (total items, n, \'c\', "esc\\n")'
    ),
    kinds: [
      'preproc',
      'keyword.import',
      'type',
      'punctuation.bracket',
      'variable',
      'punctuation.delimiter',
      'operator',
      'keyword.control',
      'keyword',
      'comment.doc',
      'keyword.declaration',
      'constructor',
      'function.definition',
      'comment',
      'function',
      'number',
      'string',
      'punctuation.special',
      'string.special',
      'string.escape',
    ],
  },
  hlsl: {
    code: lines(
      '#include "common.hlsli"',
      '#define PI 3.14159f',
      'cbuffer Params : register(b0) {',
      '    float4x4 gWorld;',
      '    float gTime;',
      '};',
      'Texture2D gTex : register(t0);',
      'SamplerState gSampler : register(s0);',
      '',
      'struct VSInput { float3 pos : POSITION; float2 uv : TEXCOORD0; };',
      'struct PSInput { float4 pos : SV_POSITION; float2 uv : TEXCOORD0; };',
      '',
      '/* vertex',
      '   shader */',
      'PSInput VSMain(VSInput input) {',
      '    PSInput o;',
      '    o.pos = mul(float4(input.pos, 1.0f), gWorld);',
      '    o.uv = input.uv * 2.0 - 1;',
      '    return o;',
      '}',
      '',
      '[numthreads(8, 8, 1)]',
      'float4 PSMain(PSInput input) : SV_TARGET {',
      '    float4 c = gTex.Sample(gSampler, input.uv);',
      '    // fade',
      '    if (c.a < 0.5 || gTime > 0x10) discard;',
      '    return saturate(c * sin(gTime * PI));',
      '}'
    ),
    kinds: [
      'preproc',
      'string',
      'constant',
      'number',
      'keyword.declaration',
      'type',
      'punctuation.delimiter',
      'keyword',
      'punctuation.bracket',
      'variable',
      'type.builtin',
      'variable.special',
      'comment',
      'function.definition',
      'property',
      'operator',
      'function',
      'keyword.control',
      'attribute',
      'function.method',
    ],
  },
  html: {
    code: lines(
      '<!DOCTYPE html>',
      '<html lang="en">',
      '<head>',
      '  <meta charset="utf-8">',
      '  <title>Demo &amp; test</title>',
      '  <style>',
      '    body { margin: 0; color: #333; }',
      '  </style>',
      '</head>',
      '<body>',
      '  <!-- main',
      '       content -->',
      '  <main id="app" class="page dark" data-count=3>',
      '    <h1>Hello, <em>world</em>!</h1>',
      '    <img src="a.png" alt=\'logo\' />',
      '    <a href="https://example.com?x=1&amp;y=2">link &#169;</a>',
      '  </main>',
      '  <script type="module">',
      '    const app = document.querySelector("#app");',
      '    app.addEventListener("click", () => console.log(42));',
      '  </script>',
      '</body>',
      '</html>'
    ),
    kinds: [
      'tag.doctype',
      'punctuation.bracket.html',
      'tag',
      'attribute',
      'punctuation.delimiter.html',
      'string',
      'string.special',
      'punctuation.bracket',
      'property',
      'punctuation.delimiter',
      'number',
      'comment',
      'keyword.declaration',
      'variable',
      'operator',
      'function.method',
    ],
  },
  java: {
    code: lines(
      'package com.example;',
      '',
      'import java.util.List;',
      'import java.util.stream.Collectors;',
      '',
      '/** A simple',
      ' *  counter. */',
      'public final class Counter<T extends Comparable<T>> implements Runnable {',
      '    private static final int MAX = 0xFF;',
      '    private final List<T> items;',
      '',
      '    @Override',
      '    public void run() {',
      '        long total = 1_000L;',
      '        double ratio = 2.5e-3;',
      "        char c = '\\n';",
      '        String text = """',
      '            multi',
      '            line""";',
      '        // filter',
      '        var names = items.stream().filter(i -> i != null).map(Object::toString).collect(Collectors.toList());',
      '        for (int i = 0; i < names.size() && i < MAX; i++) {',
      '            System.out.printf("%d %s%n", i, names.get(i));',
      '        }',
      '        /* block */',
      '        if (total > MAX || ratio == 0) throw new IllegalStateException("bad " + c);',
      '    }',
      '}'
    ),
    kinds: [
      'keyword.declaration',
      'namespace',
      'punctuation.delimiter',
      'keyword.import',
      'variable',
      'property',
      'type',
      'comment.doc',
      'operator',
      'punctuation.bracket',
      'type.builtin',
      'constant',
      'number',
      'attribute',
      'function.definition',
      'string',
      'string.escape',
      'comment',
      'function.method',
      'constant.builtin',
      'keyword.control',
      'keyword.operator',
    ],
  },
  js: {
    code: lines(
      "import { readFile } from 'node:fs/promises';",
      'export default class Store extends EventEmitter {',
      '  #items = new Map();',
      "  static VERSION = '1.0';",
      '  /**',
      '   * Add an item.',
      '   * @param {string} key',
      '   * @returns {boolean}',
      '   */',
      '  async add(key, value = null) {',
      '    if (this.#items.has(key)) return false;',
      "    const text = await readFile(`./${key}.json`, 'utf8');",
      '    this.#items.set(key, { ...JSON.parse(text), value, at: Date.now() });',
      '    return true;',
      '  }',
      '  get size() { return this.#items.size; }',
      '}',
      'const re = /^\\d+(?:\\.\\d+)?$/u;',
      'let total = 0x1F + 1_000n + 3.5e2;',
      'for (const [k, v] of new Store()) total += v?.count ?? 0;',
      '// tail comment',
      'label: while (true) { if (re.test(String(total))) break label; }'
    ),
    kinds: [
      'keyword.import',
      'punctuation.bracket',
      'variable',
      'string',
      'punctuation.delimiter',
      'keyword.control',
      'keyword.declaration',
      'type.class',
      'keyword',
      'property',
      'operator',
      'constant',
      'comment.doc',
      'keyword.jsdoc',
      'type.jsdoc',
      'variable.jsdoc',
      'function',
      'constant.builtin',
      'variable.special',
      'function.method',
      'boolean',
      'punctuation.special',
      'type',
      'string.regex',
      'number',
      'comment',
    ],
  },
  json: {
    code: lines(
      '{',
      '  "name": "highlights",',
      '  "version": "1.0.0",',
      '  "private": true,',
      '  "count": 42,',
      '  "ratio": -1.5e-3,',
      '  "tags": ["fast", "wasm", null, false],',
      '  "nested": { "escaped": "quote \\" and \\\\ and \\u00e9", "empty": {} }',
      '}'
    ),
    kinds: [
      'punctuation.bracket',
      'property.json_key',
      'punctuation.delimiter',
      'string',
      'boolean',
      'number',
      'constant.builtin',
      'string.escape',
    ],
  },
  jsx: {
    code: lines(
      "import React, { useState } from 'react';",
      '',
      '/** A counter button. */',
      'export function Counter({ initial = 0, label }) {',
      '  const [count, setCount] = useState(initial);',
      '  const items = [1, 2, 3];',
      '  return (',
      '    <div className="counter" data-count={count} onClick={() => setCount(count + 1)}>',
      '      <Button.Icon name="plus" disabled={count > 0x10} />',
      '      {label ? <span>{label}: {count}</span> : null}',
      '      <ul>',
      '        {items.map((n) => <li key={n}>{`item ${n}`}</li>)}',
      '      </ul>',
      '      {/* comment */}',
      '      <>fragment &amp; text</>',
      '    </div>',
      '  );',
      '}'
    ),
    kinds: [
      'keyword.import',
      'type',
      'punctuation.delimiter',
      'punctuation.bracket',
      'variable',
      'string',
      'comment.doc',
      'keyword.declaration',
      'function',
      'variable.parameter',
      'operator',
      'number',
      'keyword.control',
      'punctuation.bracket.jsx',
      'tag.jsx',
      'attribute.jsx',
      'punctuation.delimiter.jsx',
      'text.jsx',
      'tag.component.jsx',
      'constant.builtin',
      'function.method',
      'punctuation.special',
      'comment',
      'string.special',
    ],
  },
  kotlin: {
    code: lines(
      'package demo',
      '',
      'import kotlinx.coroutines.*',
      '',
      '/** A shape. */',
      'sealed class Shape { abstract fun area(): Double }',
      'data class Circle(val r: Double) : Shape() {',
      '    override fun area() = Math.PI * r * r',
      '}',
      '',
      '@JvmInline value class Meters(val v: Int)',
      '',
      'suspend fun main() = coroutineScope {',
      '    val shapes = listOf(Circle(1.0), Circle(2.5))',
      '    val total = shapes.sumOf { it.area() }',
      '    var count = 0x1F + 1_000L',
      '    val text = """multi',
      '        |line ${total} and $count""".trimMargin()',
      '    // loop',
      '    for ((i, s) in shapes.withIndex()) {',
      '        if (s is Circle && s.r > 1) println("$i: ${s.area()}")',
      '    }',
      '    val ok = when (count) { in 0..10 -> true; else -> false }',
      '    /* block',
      '       comment */',
      "    launch { delay(100L); println(text ?: 'c') }",
      '}'
    ),
    kinds: [
      'keyword.import',
      'variable',
      'punctuation.delimiter',
      'property',
      'operator',
      'comment.doc',
      'keyword',
      'keyword.declaration',
      'type',
      'punctuation.bracket',
      'function.definition',
      'type.builtin',
      'function',
      'attribute',
      'number',
      'function.method',
      'string',
      'punctuation.special',
      'comment',
      'keyword.control',
      'keyword.operator',
      'boolean',
    ],
  },
  less: {
    code: lines(
      '@import "base";',
      '@primary: #ff8800;',
      '@gap: 8px;',
      '// mixin',
      '.rounded(@radius: 4px) { border-radius: @radius; }',
      '.card {',
      '  color: darken(@primary, 10%);',
      '  margin: @gap * 2;',
      '  .rounded(6px);',
      '  &:hover { color: @primary; }',
      '  .title when (@gap > 4px) { font-weight: 700; }',
      '  @media (min-width: 640px) { width: ~"calc(100% - @{gap})"; }',
      '}',
      '/* block',
      '   comment */',
      '#main { .card; }'
    ),
    kinds: [
      'keyword',
      'string',
      'punctuation.delimiter',
      'variable',
      'string.special',
      'number',
      'comment',
      'selector.class',
      'punctuation.bracket',
      'property',
      'function',
      'operator',
      'selector.pseudo',
      'keyword.operator',
      'selector.id',
    ],
  },
  lisp: {
    code: lines(
      ';;; A small library',
      '(defpackage :shop (:use :cl))',
      '(in-package :shop)',
      '',
      '(defconstant +max-items+ 100 "Upper bound.")',
      '(defvar *items* nil)',
      '',
      '(defun add-item (name &key (price 0.0) (qty 1))',
      '  "Add an item to the cart."',
      '  (let ((item (list :name name :price price :qty qty)))',
      '    (push item *items*)',
      '    #| block',
      '       comment |#',
      '    (format t "added ~a (~,2f)~%" name price)',
      '    item))',
      '',
      '(defmacro with-timing ((&rest args) &body body)',
      '  `(let ((start (get-internal-real-time)))',
      '     ,@body',
      '     (list ,@args (- (get-internal-real-time) start))))',
      '',
      '(add-item "tea" :price 2.5 :qty #x10)',
      "(if (> (length *items*) 0) 'ok #\\a)"
    ),
    kinds: [
      'comment',
      'punctuation.bracket',
      'keyword.declaration',
      'string.special.symbol',
      'keyword',
      'variable',
      'number',
      'string',
      'constant.builtin',
      'function.definition',
      'function',
      'variable.special',
      'punctuation.special',
      'string.special',
    ],
  },
  lua: {
    code: lines(
      '--- A stack module.',
      '-- @module stack',
      'local Stack = {}',
      'Stack.__index = Stack',
      '',
      '--[[ block',
      'comment ]]',
      'function Stack.new(limit)',
      '  local self = setmetatable({ items = {}, limit = limit or 0x10 }, Stack)',
      '  return self',
      'end',
      '',
      'function Stack:push(value)',
      '  if #self.items >= self.limit then',
      '    error(string.format("stack full: %d\\n", self.limit))',
      '  end',
      '  self.items[#self.items + 1] = value',
      'end',
      '',
      'local s = Stack.new(3)',
      'for i = 1, 3 do s:push(i * 2.5e1) end',
      'local text = [==[multi',
      "line]==] .. 'tail'",
      'while s.items[1] ~= nil and not false do break end',
      'print(text, #s.items, nil, true, ...)',
      'goto done',
      '::done::'
    ),
    kinds: [
      'comment.doc',
      'comment',
      'keyword.declaration',
      'variable',
      'operator',
      'punctuation.bracket',
      'punctuation.delimiter',
      'property',
      'function.definition',
      'function.method',
      'function',
      'keyword.operator',
      'number',
      'keyword',
      'keyword.control',
      'string',
      'string.escape',
      'constant.builtin',
      'boolean',
    ],
  },
  markdown: {
    code: lines(
      '# Title',
      '',
      'Some *emphasis* and **strong** text with `code` and a [link](https://example.com "title").',
      '',
      '- item one',
      '- item two',
      '  1. nested',
      '> quote',
      '',
      '```js',
      'const x = 1;',
      '```',
      '',
      '| a | b |',
      '|---|---|',
      '| 1 | 2 |',
      '',
      '![alt](img.png)',
      '<div class="raw">html</div>',
      '',
      '---'
    ),
    kinds: [
      'punctuation.special',
      'title',
      'emphasis',
      'emphasis.strong',
      'text.literal',
      'punctuation.bracket',
      'link_text',
      'link_uri',
      'punctuation.list_marker',
      'punctuation.markup',
      'punctuation.delimiter',
      'keyword.declaration',
      'variable',
      'operator',
      'number',
      'punctuation.bracket.html',
      'tag',
      'attribute',
      'punctuation.delimiter.html',
      'string',
    ],
  },
  mdx: {
    code: lines(
      "import { Chart } from '../components/Chart';",
      "export const meta = { title: 'Report' };",
      '',
      '# Report',
      '',
      'Title: {meta.title}',
      '',
      'Some *text* with `code` and a [link](https://example.com).',
      '',
      '<Chart data={[1, 2, 3]} label="sales">',
      '  <strong>inner</strong>',
      '</Chart>',
      '',
      '{/* a comment',
      '    across lines */}',
      '',
      '```ts',
      'const total: number = 3;',
      '```',
      '',
      '- list item with **bold**'
    ),
    kinds: [
      'punctuation.bracket',
      'type',
      'property',
      'punctuation.delimiter',
      'string',
      'punctuation.special',
      'title',
      'variable',
      'emphasis',
      'text.literal',
      'link_text',
      'link_uri',
      'punctuation.bracket.jsx',
      'tag.component.jsx',
      'attribute.jsx',
      'punctuation.delimiter.jsx',
      'number',
      'tag.jsx',
      'comment',
      'keyword.declaration',
      'type.builtin',
      'operator',
      'punctuation.list_marker',
      'emphasis.strong',
    ],
  },
  objc: {
    code: lines(
      '#import <Foundation/Foundation.h>',
      '#define MAX_ITEMS 10',
      '',
      '/// A counter.',
      '@interface Counter : NSObject <NSCopying>',
      '@property (nonatomic, assign) NSInteger count;',
      '- (instancetype)initWithCount:(NSInteger)count;',
      '@end',
      '',
      '@implementation Counter',
      '- (instancetype)initWithCount:(NSInteger)count {',
      '    if ((self = [super init])) {',
      '        _count = count;',
      '    }',
      '    return self;',
      '}',
      '',
      '- (void)increment {',
      '    self.count += 1;',
      '    NSString *text = [NSString stringWithFormat:@"count=%ld\\n", (long)self.count];',
      '    NSArray *items = @[@1, @2.5, @YES];',
      '    NSDictionary *dict = @{ @"key": @0x10 };',
      '    /* block',
      '       comment */',
      '    if (self.count > MAX_ITEMS || items == nil) {',
      '        NSLog(@"%@ %@", text, dict); // log',
      '    }',
      '}',
      '@end'
    ),
    kinds: [
      'preproc',
      'string',
      'comment.doc',
      'keyword',
      'type',
      'punctuation.delimiter',
      'operator',
      'punctuation.bracket',
      'variable',
      'type.builtin',
      'function.definition',
      'keyword.control',
      'variable.special',
      'function.method',
      'property',
      'number',
      'string.escape',
      'punctuation.special',
      'comment',
      'constant',
      'constant.builtin',
      'function',
    ],
  },
  ocaml: {
    code: lines(
      '(* A small',
      '   module *)',
      'module Shop = struct',
      '  type item = { name : string; price : float }',
      '  exception Empty of string',
      '',
      '  let rec total = function',
      '    | [] -> 0.0',
      '    | { price; _ } :: rest -> price +. total rest',
      '',
      '  let describe ?(prefix = "item") ~name price =',
      '    Printf.sprintf "%s: %s costs %.2f\\n" prefix name price',
      '',
      '  let () =',
      '    let items = [ { name = "tea"; price = 2.5 }; { name = "cake"; price = 0x10 } ] in',
      '    match items with',
      '    | [] -> raise (Empty "no items")',
      '    | x :: _ when x.price > 1.0 ->',
      '        print_endline (describe ~name:x.name x.price);',
      '        let n = 1_000 lsl 2 land 3 in',
      '        if n <> 0 && true then print_int n',
      '    | _ -> ()',
      'end'
    ),
    kinds: [
      'comment',
      'keyword.declaration',
      'namespace',
      'operator',
      'type',
      'punctuation.bracket',
      'variable',
      'type.builtin',
      'punctuation.delimiter',
      'constructor',
      'keyword.control',
      'number',
      'function',
      'function.definition',
      'string',
      'variable.parameter',
      'string.escape',
      'property',
      'keyword.operator',
      'boolean',
    ],
  },
  perl: {
    code: lines(
      '#!/usr/bin/perl',
      'use strict;',
      'use warnings;',
      'package Shop::Cart;',
      '',
      '# a cart',
      "our $VERSION = '1.02';",
      'my %items = (tea => 2.5, cake => 0x10);',
      'my @names = sort keys %items;',
      '',
      'sub total {',
      '    my ($self, @list) = @_;',
      '    my $sum = 0;',
      '    foreach my $name (@list) {',
      '        $sum += $items{$name} if exists $items{$name};',
      '    }',
      '    return $sum;',
      '}',
      '',
      'my $text = <<"END";',
      'total: @{[ total(undef, @names) ]}',
      'END',
      'print "names: @names\\n" unless $text =~ /^total:\\s+(\\d+)/m;',
      'printf("%.2f %s\\n", $1 // 0, qq{done});',
      '=pod',
      '',
      'Documentation.',
      '',
      '=cut',
      '1;'
    ),
    kinds: [
      'comment',
      'keyword.import',
      'function',
      'punctuation.delimiter',
      'keyword.declaration',
      'namespace',
      'variable',
      'operator',
      'string',
      'punctuation.bracket',
      'string.special.symbol',
      'number',
      'function.definition',
      'keyword.control',
      'string.escape',
      'string.regex',
      'variable.special',
      'comment.doc',
    ],
  },
  php: {
    code: lines(
      '<?php',
      'declare(strict_types=1);',
      '',
      'namespace App\\Shop;',
      '',
      'use App\\Item;',
      '',
      '/**',
      ' * A cart.',
      ' */',
      'final class Cart implements \\Countable',
      '{',
      '    private const MAX = 0x10;',
      '    /** @var Item[] */',
      '    private array $items = [];',
      '',
      "    public function __construct(private readonly string $owner = 'guest') {}",
      '',
      '    public function add(Item $item, int $qty = 1): static',
      '    {',
      '        if ($qty <= 0 || count($this->items) >= self::MAX) {',
      '            throw new \\InvalidArgumentException("bad qty: {$qty}");',
      '        }',
      '        $this->items[] = $item;',
      '        // heredoc',
      '        $text = <<<EOT',
      '        owner: $this->owner',
      '        EOT;',
      "        echo $text, PHP_EOL, 'single \\'quoted\\'', 1.5e3, true, null;",
      '        return $this;',
      '    }',
      '',
      '    public function count(): int { return \\count($this->items); }',
      '}',
      '?>',
      '<p><?= $cart->count() ?></p>'
    ),
    kinds: [
      'preproc',
      'keyword',
      'punctuation.bracket',
      'variable',
      'operator',
      'number',
      'punctuation.delimiter',
      'keyword.declaration',
      'type.class',
      'comment',
      'type.builtin',
      'function.definition',
      'string',
      'keyword.control',
      'function',
      'property',
      'string.escape',
      'boolean',
      'constant.builtin',
      'punctuation.bracket.html',
      'tag',
      'function.method',
    ],
  },
  powershell: {
    code: lines(
      '#Requires -Version 7',
      '<#',
      '.SYNOPSIS',
      '  Build script.',
      '#>',
      'param(',
      '    [Parameter(Mandatory)] [string] $Target,',
      '    [int] $Retries = 3',
      ')',
      'Set-StrictMode -Version Latest',
      "$ErrorActionPreference = 'Stop'",
      '',
      'function Invoke-Build {',
      '    [CmdletBinding()]',
      '    param([string] $Name, [switch] $Clean)',
      '    # run it',
      '    $items = Get-ChildItem -Path "src\\$Name" -Filter *.ps1 | Where-Object { $_.Length -gt 0x10 }',
      '    foreach ($item in $items) {',
      '        if ($Clean -and -not (Test-Path $item)) { continue }',
      '        Write-Host "building $($item.Name) at $(Get-Date -Format \'HH:mm\')"',
      '    }',
      '    $text = @"',
      'multi $Name',
      'line',
      '"@',
      '    return @{ Count = $items.Count; Text = $text; Ok = $true; Ratio = 1.5e3 }',
      '}',
      '',
      "try { Invoke-Build -Name $Target -Clean } catch [System.IO.IOException] { throw $_ } finally { Write-Verbose 'done' }"
    ),
    kinds: [
      'comment',
      'keyword.declaration',
      'punctuation.bracket',
      'attribute',
      'type',
      'variable',
      'punctuation.delimiter',
      'operator',
      'number',
      'function',
      'variable.parameter',
      'string',
      'function.definition',
      'property',
      'variable.special',
      'keyword.operator',
      'keyword.control',
      'punctuation.special',
      'boolean',
    ],
  },
  proto: {
    code: lines(
      'syntax = "proto3";',
      '',
      'package shop.v1;',
      '',
      'import "google/protobuf/timestamp.proto";',
      'option java_package = "com.example.shop";',
      '',
      '// An item for sale.',
      'message Item {',
      '  string name = 1;',
      '  double price = 2 [deprecated = true];',
      '  repeated string tags = 3;',
      '  map<string, int32> counts = 4;',
      '  oneof kind {',
      '    Physical physical = 5;',
      '    Digital digital = 6;',
      '  }',
      '  reserved 7, 8 to 0x10;',
      '  enum Status { STATUS_UNSPECIFIED = 0; ACTIVE = 1; }',
      '  google.protobuf.Timestamp created = 9;',
      '}',
      '',
      '/* block',
      '   comment */',
      'service Shop {',
      '  rpc GetItem(GetItemRequest) returns (Item) {}',
      '  rpc Watch(stream Item) returns (stream Item);',
      '}'
    ),
    kinds: [
      'keyword',
      'operator',
      'string',
      'punctuation.delimiter',
      'keyword.declaration',
      'namespace',
      'keyword.import',
      'property',
      'comment',
      'type',
      'punctuation.bracket',
      'type.builtin',
      'number',
      'boolean',
      'variable',
      'constant',
      'function.definition',
    ],
  },
  python: {
    code: lines(
      '"""Module docstring',
      'across lines."""',
      'from __future__ import annotations',
      'import asyncio',
      'from dataclasses import dataclass, field',
      '',
      'MAX_ITEMS = 0x10',
      '',
      '@dataclass(frozen=True)',
      'class Item:',
      '    name: str',
      '    price: float = 0.0',
      '    tags: list[str] = field(default_factory=list)',
      '',
      '    def __str__(self) -> str:',
      '        return f"{self.name}: {self.price:.2f}"',
      '',
      'async def total(items: list[Item], *, ratio: float = 1e-2) -> float:',
      '    # sum prices',
      '    result = sum(i.price for i in items if i.price > 0)',
      '    await asyncio.sleep(0.1)',
      '    match items:',
      '        case [Item(name="tea"), *rest]:',
      '            print(rest, r"raw\\n", b\'bytes\', None, True)',
      '        case _:',
      '            pass',
      '    return result * ratio if result else 0',
      '',
      'if __name__ == "__main__":',
      '    items = [Item("tea", 2.5), Item(\'cake\', 1_000)]',
      '    print(asyncio.run(total(items)))  # run'
    ),
    kinds: [
      'string',
      'keyword.import',
      'variable',
      'punctuation.delimiter',
      'constant',
      'operator',
      'number',
      'attribute',
      'punctuation.bracket',
      'boolean',
      'keyword.declaration',
      'type.class',
      'type.builtin',
      'function',
      'function.definition',
      'variable.special',
      'keyword.control',
      'punctuation.special',
      'variable.parameter',
      'type',
      'comment',
      'property',
      'keyword.operator',
      'function.method',
      'constant.builtin',
    ],
  },
  r: {
    code: lines(
      "#' Roxygen comment",
      'library(dplyr)',
      '',
      'fib <- function(n = 10, ...) {',
      '  if (n <= 1L) return(n)',
      '  fib(n - 1) + fib(n - 2)',
      '}',
      '',
      'df <- data.frame(x = 1:10, y = rnorm(10))',
      'result <- df %>%',
      '  filter(x > 5) |>',
      '  mutate(z = x * 2, `odd name` = TRUE)',
      'print(sprintf("%.2f\\n", result$y[[1]]))',
      'v <- c(a = 1e-3, b = 0x1F, c = NA_integer_, d = NULL, e = Inf)',
      'for (i in seq_len(3)) next',
      'sq = \\(w) w^2',
      'raw <- r"(multi',
      'line)"',
      'pkg::fun(.hidden, obj@slot) # note'
    ),
    kinds: [
      'comment.doc',
      'function',
      'punctuation.bracket',
      'variable',
      'function.definition',
      'operator',
      'keyword.declaration',
      'variable.parameter',
      'number',
      'punctuation.delimiter',
      'variable.special',
      'keyword.control',
      'boolean',
      'string',
      'string.escape',
      'property',
      'constant.builtin',
      'keyword.operator',
      'namespace',
      'comment',
    ],
  },
  ruby: {
    code: lines(
      '# frozen_string_literal: true',
      "require 'json'",
      '',
      'module Shop',
      '  # A shopping cart.',
      '  class Cart',
      '    include Enumerable',
      '    MAX = 0x10',
      '    attr_reader :items',
      '',
      "    def initialize(owner = 'guest', **opts)",
      '      @owner = owner',
      '      @items = []',
      '      @opts = opts',
      '    end',
      '',
      '    def add(item, qty: 1)',
      '      raise ArgumentError, "bad qty: #{qty}" unless qty.positive? && items.size < MAX',
      '      @items << { item: item, qty: qty }',
      '      self',
      '    end',
      '',
      '    def summary',
      '      text = <<~EOS',
      '        owner: #{@owner}',
      '        total: #{items.sum { |i| i[:qty] } * 2.5e1}',
      '      EOS',
      '      text.gsub(/total:\\s+(\\d+)/) { "TOTAL #{$1}" } =~ %r{owner}',
      '      [:ok, nil, true, :"quoted sym", \'single\'] # done',
      '    end',
      '  end',
      'end',
      '',
      '=begin',
      'block comment',
      '=end',
      'puts Shop::Cart.new.add(:tea).summary'
    ),
    kinds: [
      'comment',
      'function',
      'string',
      'keyword.declaration',
      'type',
      'constant',
      'operator',
      'number',
      'string.special.symbol',
      'function.definition',
      'punctuation.bracket',
      'variable',
      'punctuation.delimiter',
      'variable.special',
      'keyword.control',
      'punctuation.special',
      'function.method',
      'string.regex',
      'string.escape',
      'constant.builtin',
      'boolean',
    ],
  },
  rust: {
    code: lines(
      'use std::collections::HashMap;',
      'use std::fmt;',
      '',
      '/// A shape.',
      '#[derive(Debug, Clone, PartialEq)]',
      'pub enum Shape {',
      '    Circle { r: f64 },',
      '    Rect(f64, f64),',
      '}',
      '',
      'impl fmt::Display for Shape {',
      "    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {",
      '        match self {',
      '            Shape::Circle { r } => write!(f, "circle({r})"),',
      '            Shape::Rect(w, h) => write!(f, "rect({}x{})", w, h),',
      '        }',
      '    }',
      '}',
      '',
      "pub fn total<'a, I: Iterator<Item = &'a Shape>>(shapes: I) -> f64 {",
      '    shapes.map(|s| match s {',
      '        Shape::Circle { r } => std::f64::consts::PI * r * r,',
      '        Shape::Rect(w, h) => w * h,',
      '    }).sum()',
      '}',
      '',
      'fn main() {',
      '    let mut counts: HashMap<&str, u32> = HashMap::new();',
      '    let shapes = vec![Shape::Circle { r: 1.5 }, Shape::Rect(2.0, 0x10 as f64)];',
      '    let raw = r#"multi',
      'line"#;',
      '    *counts.entry("n").or_insert(0) += 1_000u32;',
      '    // print',
      '    if let Some(&n) = counts.get("n") { println!("{} {}\\n", raw, n); }',
      '    /* block */',
      "    let bytes = b'a' as usize + '\\n' as usize;",
      '    assert!(bytes != 0, "never");',
      '}'
    ),
    kinds: [
      'keyword.import',
      'variable',
      'punctuation.delimiter',
      'property',
      'type',
      'comment.doc',
      'attribute',
      'punctuation.bracket',
      'keyword',
      'keyword.declaration',
      'type.builtin',
      'function',
      'keyword.control',
      'function.definition',
      'operator',
      'variable.special',
      'variable.parameter',
      'label',
      'string',
      'function.method',
      'constant',
      'number',
      'keyword.operator',
      'comment',
      'string.escape',
    ],
  },
  sass: {
    code: lines(
      '@use "base"',
      '$primary: #ff8800',
      '$gap: 8px',
      '// mixin',
      '=rounded($radius: 4px)',
      '  border-radius: $radius',
      '.card',
      '  color: darken($primary, 10%)',
      '  margin: $gap * 2',
      '  +rounded(6px)',
      '  &:hover',
      '    color: $primary',
      '  @media (min-width: 640px)',
      '    width: calc(100% - #{$gap})',
      '/* block',
      '   comment */',
      '@each $name in a, b',
      '  .#{$name}',
      '    content: "#{$name}"'
    ),
    kinds: [
      'keyword',
      'string',
      'variable',
      'punctuation.delimiter',
      'string.special',
      'number',
      'comment',
      'function',
      'punctuation.bracket',
      'property',
      'selector.class',
      'operator',
      'selector.pseudo',
      'punctuation.special',
      'keyword.operator',
      'constant.builtin',
    ],
  },
  scala: {
    code: lines(
      'package shop',
      '',
      'import scala.collection.mutable',
      'import scala.util.{Try, Success}',
      '',
      '/** A shape. */',
      'sealed trait Shape { def area: Double }',
      'final case class Circle(r: Double) extends Shape {',
      '  override def area: Double = math.Pi * r * r',
      '}',
      'case object Empty extends Shape { val area = 0.0 }',
      '',
      'object Main extends App {',
      '  private val MAX = 0x10',
      '  val shapes: List[Shape] = List(Circle(1.5), Empty)',
      '  val total = shapes.map(_.area).sum',
      '  var count = 1_000L',
      '  // interpolate',
      '  val text = s"total=$total count=${count + 1}"',
      '  val block = """multi',
      '    |line""".stripMargin',
      '  shapes.foreach {',
      '    case Circle(r) if r > 1 => println(f"circle $r%.1f\\n")',
      '    case _ => ()',
      '  }',
      '  /* block',
      '     comment */',
      '  for (i <- 0 until MAX if i % 2 == 0) yield i * 2.5e1',
      '  Try(text.length) match { case Success(n) => count += n; case _ => }',
      "  val sym = 'c'",
      '  val ok = true',
      '}'
    ),
    kinds: [
      'keyword.import',
      'namespace',
      'punctuation.delimiter',
      'punctuation.bracket',
      'type',
      'comment.doc',
      'keyword',
      'keyword.declaration',
      'function.definition',
      'keyword.control',
      'variable',
      'operator',
      'number',
      'constant',
      'function.method',
      'property',
      'comment',
      'function',
      'string',
      'punctuation.special',
      'string.escape',
      'boolean',
    ],
  },
  scss: {
    code: lines(
      '@use "sass:math";',
      '$primary: #ff8800 !default;',
      '$gap: 8px;',
      '// mixin',
      '@mixin rounded($radius: 4px) { border-radius: $radius; }',
      '.card {',
      '  color: darken($primary, 10%);',
      '  margin: math.div($gap, 2) * 3;',
      '  @include rounded(6px);',
      '  &:hover { color: $primary; }',
      '  @media (min-width: 640px) { width: calc(100% - #{$gap}); }',
      '  @if $gap > 4px { font-weight: 700; } @else { font-weight: 400; }',
      '}',
      '/* block',
      '   comment */',
      '@each $name, $value in (a: 1, b: 2) { .#{$name} { order: $value; } }',
      '%placeholder { margin: 0; }',
      '#main { @extend %placeholder; }'
    ),
    kinds: [
      'keyword',
      'string',
      'punctuation.delimiter',
      'variable',
      'string.special',
      'number',
      'comment',
      'function',
      'punctuation.bracket',
      'property',
      'selector.class',
      'constant.builtin',
      'operator',
      'selector.pseudo',
      'punctuation.special',
      'keyword.operator',
      'selector.id',
    ],
  },
  sql: {
    code: lines(
      '-- schema',
      'CREATE TABLE users (',
      '  id INTEGER PRIMARY KEY,',
      "  name VARCHAR(64) NOT NULL DEFAULT 'anon',",
      '  created DATE,',
      '  active BOOLEAN DEFAULT true',
      ');',
      '',
      '/* seed',
      '   data */',
      "INSERT INTO users (id, name) VALUES (1, 'it''s'), (2, \"quoted\");",
      '',
      'SELECT u.id, COUNT(*) AS n, MAX(o.total)',
      'FROM users u LEFT JOIN orders o ON o.user_id = u.id',
      "WHERE u.active = true AND o.total >= 10.5 AND u.name LIKE 'A%' OR o.id IS NULL",
      'GROUP BY u.id HAVING COUNT(*) > 1',
      'ORDER BY n DESC LIMIT 10;',
      '',
      'UPDATE users SET name = $1 WHERE id = ?;',
      "SELECT CASE WHEN total > 100 THEN 'big' ELSE 'small' END, $body$dollar $ quoted",
      'across lines$body$ FROM orders;'
    ),
    kinds: [
      'comment',
      'keyword',
      'function',
      'punctuation.bracket',
      'variable',
      'type.builtin',
      'punctuation.delimiter',
      'number',
      'keyword.operator',
      'constant.builtin',
      'string',
      'boolean',
      'operator',
      'variable.special',
      'keyword.control',
    ],
  },
  svelte: {
    code: lines(
      '<script lang="ts">',
      "  import { onMount } from 'svelte';",
      '  export let items: string[] = [];',
      '  let count = 0;',
      '  $: doubled = count * 2;',
      '  onMount(() => { count = 0x10; });',
      '</script>',
      '',
      '<!-- list',
      '     across lines -->',
      '<h1 class="title" class:active={count > 0} on:click={() => count++}>Count: {count}</h1>',
      '{#if items.length > 0}',
      '  <ul>',
      '    {#each items as item, i (item)}',
      '      <li>{i}: {item.toUpperCase()}</li>',
      '    {/each}',
      '  </ul>',
      '{:else if count}',
      '  <p>{@html "<b>none</b>"}</p>',
      '{:else}',
      '  <slot />',
      '{/if}',
      '{#await promise then value}{value}{/await}',
      '',
      '<style>',
      '  .title { color: red; font-size: 1.5rem; }',
      '</style>'
    ),
    kinds: [
      'punctuation.bracket.html',
      'tag',
      'attribute',
      'punctuation.delimiter.html',
      'string',
      'keyword.import',
      'punctuation.bracket',
      'variable',
      'punctuation.delimiter',
      'keyword.declaration',
      'operator',
      'number',
      'function',
      'comment',
      'punctuation.special',
      'keyword.control',
      'property',
      'keyword',
      'function.method',
      'selector.class',
      'constant.builtin',
    ],
  },
  swift: {
    code: lines(
      'import Foundation',
      '',
      '/// A shape.',
      'protocol Shape { var area: Double { get } }',
      '',
      'struct Circle: Shape {',
      '    let r: Double',
      '    var area: Double { .pi * r * r }',
      '}',
      '',
      'enum Kind: String, CaseIterable { case small, large = "big" }',
      '',
      'final class Cart<T: Shape> {',
      '    private(set) var items: [T] = []',
      '    static let max = 0x10',
      '',
      '    @discardableResult',
      '    func add(_ item: T, qty: Int = 1) throws -> Self {',
      '        guard qty > 0, items.count < Self.max else { throw CartError.full }',
      '        items.append(item)',
      '        // interpolation',
      '        print("added \\(item) x\\(qty) total=\\(items.reduce(0) { $0 + $1.area })\\n")',
      '        let text = """',
      '        multi',
      '        line',
      '        """',
      '        let raw = #"raw "quoted""#',
      '        if let first = items.first as? Circle, first.r > 1.5e1 || text.isEmpty { print(raw, nil as Int?, true) }',
      '        /* block',
      '           comment */',
      '        return self',
      '    }',
      '}'
    ),
    kinds: [
      'keyword.import',
      'type',
      'comment.doc',
      'keyword.declaration',
      'punctuation.bracket',
      'variable',
      'punctuation.delimiter',
      'type.builtin',
      'property',
      'operator',
      'keyword.control',
      'string',
      'keyword',
      'number',
      'attribute',
      'function.definition',
      'variable.parameter',
      'function.method',
      'comment',
      'function',
      'punctuation.special',
      'string.escape',
      'keyword.operator',
      'constant.builtin',
      'boolean',
      'variable.special',
    ],
  },
  terraform: {
    code: lines(
      'terraform {',
      '  required_version = ">= 1.5"',
      '  required_providers { aws = { source = "hashicorp/aws", version = "~> 5.0" } }',
      '}',
      '',
      '# the bucket',
      'variable "name" {',
      '  type    = string',
      '  default = "demo"',
      '}',
      '',
      'locals {',
      '  tags  = { env = var.env, owner = "team-${var.name}" }',
      '  count = length(var.zones) > 0 ? 3 : 1',
      '}',
      '',
      'resource "aws_s3_bucket" "logs" {',
      '  bucket = "${local.tags.env}-logs"',
      '  count  = local.count',
      '  /* block',
      '     comment */',
      '  versioning { enabled = true }',
      '  lifecycle { ignore_changes = [tags] }',
      '  user_data = <<-EOT',
      '    #!/bin/bash',
      '    echo ${var.name} 1.5e3',
      '  EOT',
      '}',
      '',
      'output "arn" { value = aws_s3_bucket.logs[0].arn }'
    ),
    kinds: [
      'keyword.declaration',
      'punctuation.bracket',
      'property',
      'operator',
      'string',
      'punctuation.delimiter',
      'comment',
      'type.builtin',
      'variable.special',
      'punctuation.special',
      'function',
      'number',
      'boolean',
      'variable',
    ],
  },
  toml: {
    code: lines(
      '# config',
      'title = "Demo"',
      'version = 1.2',
      'enabled = true',
      'created = 1979-05-27T07:32:00Z',
      'tags = ["a", \'b\', 0x1F, -3.5e2, inf]',
      '',
      '[server]',
      'host = "localhost"',
      'ports = [8080, 8081]',
      '"quoted key" = \'literal \\n\'',
      'multi = """',
      'line one \\u00e9',
      'line two"""',
      '',
      '[[items]]',
      'name = "tea"',
      'price = 2.50',
      '',
      '[items.meta]',
      'nested.key = { x = 1, y = [true, false] }',
      "raw = '''",
      'C:\\path\\to',
      "'''"
    ),
    kinds: [
      'comment',
      'property',
      'operator',
      'string',
      'number',
      'constant',
      'string.special',
      'punctuation.bracket',
      'punctuation.delimiter',
      'string.escape',
    ],
  },
  ts: {
    code: lines(
      "import type { Readable } from 'node:stream';",
      "import { EventEmitter } from 'node:events';",
      '',
      'export interface Item<T = unknown> {',
      '  readonly id: string;',
      '  value?: T;',
      '  tags: string[];',
      '}',
      '',
      'type Handler<K extends keyof Events> = (payload: Events[K]) => void | Promise<void>;',
      'enum Kind { Small = 1, Large = 0x10 }',
      '',
      'export abstract class Store<T extends Item> extends EventEmitter implements Iterable<T> {',
      '  #items = new Map<string, T>();',
      "  protected static readonly VERSION = '1.0' as const;",
      '',
      '  constructor(private readonly name: string, public limit = 1_000) { super(); }',
      '',
      '  /** Add an item. */',
      '  async add(item: T, at: Date = new Date()): Promise<boolean> {',
      '    if (this.#items.has(item.id) || this.#items.size >= this.limit) return false;',
      '    this.#items.set(item.id, { ...item, tags: [...item.tags, `at:${at.toISOString()}`] });',
      '    return true;',
      '  }',
      '',
      "  abstract validate(item: T): item is T & { value: NonNullable<T['value']> };",
      '  *[Symbol.iterator](): Iterator<T> { yield* this.#items.values(); }',
      '}',
      '',
      "declare module 'x' { export const y: number; }",
      'const re = /^(\\d+)\\.(\\d+)$/;',
      'let n: number | null = null as unknown as 3.5e2;',
      '/* block',
      '   comment */',
      'export function total<T extends Item>(items: readonly T[]): number { return items.length satisfies number; }',
      '// tail'
    ),
    kinds: [
      'keyword.import',
      'variable',
      'punctuation.bracket',
      'type',
      'string',
      'punctuation.delimiter',
      'keyword.declaration',
      'operator',
      'constant',
      'keyword',
      'punctuation.special',
      'type.builtin',
      'property',
      'variable.parameter',
      'number',
      'type.class',
      'function',
      'variable.special',
      'comment.doc',
      'keyword.control',
      'function.method',
      'boolean',
      'string.regex',
      'constant.builtin',
      'comment',
    ],
  },
  tsx: {
    code: lines(
      "import React, { useState, type FC } from 'react';",
      '',
      'interface Props { initial?: number; label: string }',
      '',
      '/** A counter button. */',
      'export const Counter: FC<Props> = ({ initial = 0, label }) => {',
      '  const [count, setCount] = useState<number>(initial);',
      '  const items: readonly number[] = [1, 2, 3];',
      '  return (',
      '    <div className="counter" data-count={count} onClick={() => setCount(count + 1)}>',
      '      <Button.Icon name="plus" disabled={count > 0x10} />',
      '      {label ? <span>{label}: {count as number}</span> : null}',
      '      <ul>',
      '        {items.map((n) => <li key={n}>{`item ${n}`}</li>)}',
      '      </ul>',
      '      {/* comment',
      '          across lines */}',
      '      <>fragment &amp; text</>',
      '    </div>',
      '  );',
      '};',
      'function identity<T,>(x: T): T { return x; }'
    ),
    kinds: [
      'keyword.import',
      'type',
      'punctuation.delimiter',
      'punctuation.bracket',
      'variable',
      'keyword.declaration',
      'string',
      'property',
      'punctuation.special',
      'type.builtin',
      'comment.doc',
      'constant',
      'operator',
      'number',
      'keyword',
      'keyword.control',
      'punctuation.bracket.jsx',
      'tag.jsx',
      'attribute.jsx',
      'punctuation.delimiter.jsx',
      'function',
      'text.jsx',
      'tag.component.jsx',
      'constant.builtin',
      'function.method',
      'variable.parameter',
      'comment',
      'string.special',
    ],
  },
  vue: {
    code: lines(
      '<script setup lang="ts">',
      "import { ref, computed } from 'vue';",
      'const props = defineProps<{ items: string[]; max?: number }>();',
      'const count = ref(0);',
      'const doubled = computed(() => count.value * 2);',
      'function add() { if (count.value < (props.max ?? 0x10)) count.value++; }',
      '</script>',
      '',
      '<template>',
      '  <!-- list',
      '       across lines -->',
      '  <div :class="{ active: count > 0 }" @click="add" v-bind:title="\'count\'">',
      '    <h1 v-if="items.length">{{ count }} / {{ doubled.toFixed(1) }}</h1>',
      '    <ul v-else>',
      '      <li v-for="(item, i) in items" :key="i" v-html="item"></li>',
      '    </ul>',
      '    <slot name="footer" />',
      '  </div>',
      '</template>',
      '',
      '<style scoped>',
      '.active { color: red; font-size: 1.5rem; }',
      '</style>'
    ),
    kinds: [
      'punctuation.bracket.html',
      'tag',
      'attribute',
      'punctuation.delimiter.html',
      'string',
      'keyword.import',
      'punctuation.bracket',
      'variable',
      'punctuation.delimiter',
      'keyword.declaration',
      'operator',
      'property',
      'function',
      'number',
      'keyword.control',
      'comment',
      'punctuation.special',
      'function.method',
      'keyword',
      'selector.class',
      'constant.builtin',
    ],
  },
  wat: {
    code: lines(
      ';; a small module',
      '(module',
      '  (import "env" "log" (func $log (param i32)))',
      '  (memory (export "memory") 1)',
      '  (global $counter (mut i32) (i32.const 0))',
      '  (data (i32.const 8) "hello\\n")',
      '  (type $binop (func (param i32 i32) (result i32)))',
      '',
      '  (; block',
      '     comment ;)',
      '  (func $add (export "add") (type $binop) (param $a i32) (param $b i32) (result i32)',
      '    (local $tmp i64)',
      '    (local.set $tmp (i64.extend_i32_u (local.get $a)))',
      '    (block $exit',
      '      (loop $again',
      '        (br_if $exit (i32.eqz (local.get $b)))',
      '        (global.set $counter (i32.add (global.get $counter) (i32.const 1)))',
      '        (local.set $b (i32.sub (local.get $b) (i32.const 1)))',
      '        (br $again)))',
      '    (if (result i32) (i32.gt_s (local.get $a) (i32.const -5))',
      '      (then (local.get $a))',
      '      (else (f32.const 1.5e2) (drop) (i32.const 0xff))))',
      '  (start $add)',
      ')'
    ),
    kinds: [
      'comment',
      'punctuation.bracket',
      'keyword',
      'string',
      'variable',
      'type.builtin',
      'number',
      'function',
      'string.escape',
      'keyword.control',
    ],
  },
  wgsl: {
    code: lines(
      '// vertex shader',
      'struct Uniforms {',
      '  mvp: mat4x4<f32>,',
      '  time: f32,',
      '};',
      '@group(0) @binding(0) var<uniform> u: Uniforms;',
      '@group(0) @binding(1) var tex: texture_2d<f32>;',
      '@group(0) @binding(2) var samp: sampler;',
      '',
      'struct VertexOut {',
      '  @builtin(position) pos: vec4<f32>,',
      '  @location(0) uv: vec2<f32>,',
      '};',
      '',
      'const PI: f32 = 3.14159;',
      'override scale: f32 = 1.0;',
      '',
      '/* block',
      '   comment */',
      'fn lambert(n: vec3<f32>, l: vec3<f32>) -> f32 {',
      '  return max(dot(normalize(n), l), 0.0);',
      '}',
      '',
      '@vertex',
      'fn vs_main(@location(0) in_pos: vec3<f32>, @builtin(vertex_index) idx: u32) -> VertexOut {',
      '  var out: VertexOut;',
      '  let p = u.mvp * vec4<f32>(in_pos * scale, 1.0);',
      '  out.pos = p;',
      '  out.uv = p.xy * 0.5 + 0.5;',
      '  if (idx > 0x10u && u.time != 0.0) { out.uv.x = f32(idx) * 1e-2; }',
      '  loop { break; }',
      '  let ok = true;',
      '  return out;',
      '}'
    ),
    kinds: [
      'comment',
      'keyword.declaration',
      'type',
      'punctuation.bracket',
      'variable',
      'punctuation.delimiter',
      'type.builtin',
      'operator',
      'attribute',
      'number',
      'keyword',
      'constant',
      'function.definition',
      'keyword.control',
      'function',
      'property',
      'boolean',
    ],
  },
  xml: {
    code: lines(
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<!DOCTYPE catalog [',
      '  <!ELEMENT catalog (item*)>',
      '  <!ENTITY brand "ACME">',
      ']>',
      '<!-- a catalog',
      '     across lines -->',
      '<catalog xmlns="urn:shop" xmlns:x="urn:extra" version="2">',
      '  <item id="a1" x:kind=\'tea\' price="2.50">',
      '    <name>&brand; Tea &amp; more &#169;</name>',
      '    <desc><![CDATA[Fresh <b>leaves</b>',
      '      & such]]></desc>',
      '    <empty/>',
      '    <?render mode="fast"?>',
      '  </item>',
      '</catalog>'
    ),
    kinds: [
      'preproc',
      'tag.doctype',
      'comment',
      'punctuation.bracket.html',
      'tag',
      'attribute',
      'punctuation.delimiter.html',
      'string',
      'string.special',
      'text.literal',
    ],
  },
  yaml: {
    code: lines(
      '# config',
      'version: 1.2',
      'name: "demo"',
      'enabled: true',
      'created: 2024-01-01',
      "tags: [fast, 'wasm', 0x1F, -3.5e2, ~]",
      'server:',
      '  host: localhost',
      '  ports:',
      '    - 8080',
      '    - 8081',
      '  env: &defaults',
      '    DEBUG: no',
      '    PATH: /usr/bin',
      '  extra: *defaults',
      'description: |',
      '  multi line',
      '  literal block',
      'folded: >-',
      '  folded',
      '  text',
      '? complex key',
      ': value',
      '!!str tagged: !custom {a: 1, b: null}',
      '---',
      'second: document',
      '...'
    ),
    kinds: [
      'comment',
      'property',
      'punctuation.delimiter',
      'number',
      'string',
      'boolean',
      'punctuation.bracket',
      'constant.builtin',
      'type',
      'punctuation.special',
    ],
  },
  zig: {
    code: lines(
      'const std = @import("std");',
      'const Allocator = std.mem.Allocator;',
      '',
      '/// A shape.',
      'pub const Shape = union(enum) {',
      '    circle: f64,',
      '    rect: struct { w: f64, h: f64 },',
      '',
      '    pub fn area(self: Shape) f64 {',
      '        return switch (self) {',
      '            .circle => |r| std.math.pi * r * r,',
      '            .rect => |r| r.w * r.h,',
      '        };',
      '    }',
      '};',
      '',
      'pub fn main() !void {',
      '    var gpa = std.heap.GeneralPurposeAllocator(.{}){};',
      '    defer _ = gpa.deinit();',
      '    const alloc: Allocator = gpa.allocator();',
      '    var list = std.ArrayList(Shape).init(alloc);',
      '    defer list.deinit();',
      '    try list.append(.{ .circle = 1.5 });',
      '    try list.append(.{ .rect = .{ .w = 2.0, .h = 0x10 } });',
      '    // sum',
      '    var total: f64 = 0;',
      '    for (list.items, 0..) |s, i| {',
      '        if (i > 1_000 or s.area() == 0) break;',
      '        total += s.area();',
      '    }',
      '    const text =',
      '        \\\\multi',
      '        \\\\line',
      '    ;',
      "    comptime var n: u8 = 'a';",
      '    std.debug.print("{d} {s} {c} {any}\\n", .{ total, text, n, null });',
      '    while (n < 3.5e2) : (n += 1) {}',
      '    inline for (.{ true, false }) |b| if (b) unreachable;',
      '}'
    ),
    kinds: [
      'keyword.declaration',
      'variable',
      'operator',
      'keyword.import',
      'punctuation.bracket',
      'string',
      'punctuation.delimiter',
      'type',
      'property',
      'comment.doc',
      'keyword',
      'type.builtin',
      'function.definition',
      'variable.parameter',
      'keyword.control',
      'function.method',
      'variable.special',
      'number',
      'comment',
      'keyword.operator',
      'string.escape',
      'constant.builtin',
      'boolean',
    ],
  },
};
